-- GENERATED by tools/gen-pc-seed.mjs from Gemini-extracted PC blocks. AI-extracted from

-- noisy OCR — everything confirmed=false (needs review). Load AFTER schema.sql + seed.sql.


insert into courses values ('pc','Peace Corps Waray','war','grammar-spine') on conflict (id) do nothing;

insert into phases values ('pc-p1','pc',1,'Foundations (Lessons 1–10)','equational sentences & the pronoun classes') on conflict (id) do nothing;

insert into units values ('pc-u1','pc-p1',1,'Pronoun classes & verbs',null,null) on conflict (id) do nothing;

insert into lessons (id,unit_id,ord,title) values
  ('pc-l1','pc-u1',1,'Lesson 1 — I-Class Personal Pronouns'),
  ('pc-l2','pc-u1',2,'Lesson 2 — I-Class Markers'),
  ('pc-l8','pc-u1',3,'Lesson 8 — III-Class Personal Pronouns'),
  ('pc-l9','pc-u1',4,'Lesson 9 — III-Class ha+ Beneficiary') on conflict (id) do nothing;

insert into dictionary (waray,kind,meaning,pos,confirmed) values
  ('Tátay','word','father','noun',false),
  ('Amerikáno','word','American','noun',false),
  ('Asáwa','word','wife','noun',false),
  ('Babáye','word','woman (female)','noun',false),
  ('Buótan','word','nice','adj',false),
  ('Riko','word','rich','adj',false),
  ('Estudyánte','word','student','noun',false),
  ('Mahúsay','word','pretty, beautiful (female)','adj',false),
  ('Gwápo','word','handsome (male)','adj',false),
  ('Sángkay','word','friend','noun',false),
  ('Nánay','word','mother','noun',false),
  ('mapasô','word','hot','adj',false),
  ('Kristohánon','word','Christian','noun',false),
  ('maduróto','word','industrious','adj',false),
  ('makusóg','word','strong (person)','adj',false),
  ('laláke','word','man (male)','noun',false),
  ('maéstro','word','teacher (male)','noun',false),
  ('Misyonaryo','word','missionary','noun',false),
  ('Pilipíno','word','Filipino (male)','noun',false),
  ('Hataás','word','tall, long','adj',false),
  ('Matámbok','word','fat','adj',false),
  ('mga','word','pluralizer','marker',false),
  ('Lingkúran','word','Chair','noun',false),
  ('Báso','word','Glass','noun',false),
  ('Bátà','word','Child, baby','noun',false),
  ('Bóla','word','Ball','noun',false),
  ('Malabad','word','Naughty','adj',false),
  ('Dakú','word','Big','adj',false),
  ('Gutiay','word','Small','adj',false),
  ('Kláse','word','Class','noun',false),
  ('Lamésa','word','Table','noun',false),
  ('Léksyon','word','Lesson','noun',false),
  ('madíg-on','word','Strong (things)','adj',false),
  ('malídong','word','Round','adj',false),
  ('makuri','word','Difficult','adj',false),
  ('maúpay','word','Good','adj',false),
  ('mahúsay','word','Pretty','adj',false),
  ('Papél','word','Paper','noun',false),
  ('Punô','word','Full','adj',false),
  ('Mabuság','word','White','adj',false),
  ('masayón','word','Easy','adj',false),
  ('-bisíta','word','visit','verb',false),
  ('bisita','word','visitor','noun',false),
  ('biyáhe','word','trip, journey','noun',false),
  ('Diyós','word','God','noun',false),
  ('gúgma','word','love','noun',false),
  ('-higdà','word','to lay down','verb',false),
  ('iglésiya','word','church','noun',false),
  ('Kaádlawan','word','birthday','noun',false),
  ('kasingkásing','word','heart','noun',false),
  ('kátre','word','bed','noun',false),
  ('láwas','word','body','noun',false),
  ('manók','word','chicken','noun',false),
  ('násud','word','nation','noun',false),
  ('nawóng','word','face','noun',false),
  ('ngáran','word','name','noun',false),
  ('-upód','word','to accompany, to go with','verb',false),
  ('pagkáon','word','food','noun',false),
  ('-karáwat','word','to accept, receive','verb',false),
  ('-súgat','word','to meet','verb',false),
  ('peligróso','word','dangerous','adj',false),
  ('sinehán','word','movie house','noun',false),
  ('siyudád','word','city','noun',false),
  ('telebisyon','word','television','noun',false),
  ('-tútdò','word','to teach','verb',false),
  ('umá','word','farm','noun',false),
  ('abót','word','to arrive','verb',false),
  ('ámpo','word','to pray','verb',false),
  ('bendisyon','word','blessing','noun',false),
  ('búgtò','word','brother/sister','noun',false),
  ('hátag','word','to give','verb',false),
  ('lugár','word','place','noun',false),
  ('píli','word','to choose','verb',false),
  ('sárig','word','to trust','verb',false),
  ('surát','word','to write','verb',false),
  ('siring','word','to speak/talk','verb',false),
  ('upod','word','to go with/accompany','verb',false),
  ('wáli','word','to preach','verb',false)
  on conflict (waray) do nothing;

insert into expressions (id,waray,translation) values
  (20001,'Pilipino ka.','You are a Filipino.'),
  (20002,'Amerikano ako.','I am an American.'),
  (20003,'Estudyante hiya.','He/She is a student.'),
  (20004,'Mahusay hiya.','She is beautiful.'),
  (20005,'Hataas ako.','I am tall.'),
  (20006,'Riko hira.','They are rich.'),
  (20007,'Mga lalake kita.','We (incl) are men (male).'),
  (20008,'Mga babaye kami.','We (excl) are women (female).'),
  (20009,'Mga sangkay kita.','We (incl) are friends.'),
  (20010,'Mga Pilipino kami.','We (excl) are Filipinos.'),
  (20011,'Ako hi Peter.','I am Peter.'),
  (20012,'Hiya hi Bebing.','She is Bebing.'),
  (20013,'Pilipino hi Pablo.','Pablo is Filipino.'),
  (20014,'Hira Perla ngan Tessie.','They are Perla and Tessie.'),
  (20015,'Buotan hi Ernesto.','Ernesto is nice.'),
  (20016,'Riko hira Marvin ngan Annie.','Marvin and Annie are rich.'),
  (20017,'Mahusay an lamesa.','The table is beautiful.'),
  (20018,'Mabusag an papel.','The paper is white.'),
  (20019,'Malabad an mga bata.','The children are naughty.'),
  (20020,'Madig-on an mga lingkuran.','The chairs are strong.'),
  (20021,'Mahuram an panday hin saruwal para ha iya apoy.','The carpenter will borrow trousers for his/her grandparent.'),
  (20022,'Pinmalit hi Lorie hin prutas dida ha tindahan para ha pamilya niya.','Lorie bought fruit there at the store for her family.'),
  (20023,'Kinmaon kita hiton nga mangga didto ha balay niyo.','We ate that mango there at your (pl) house.'),
  (20024,'Sinmimba an mga tawo didto ha mga diyos-diyos.','The people worshipped there at the idols.'),
  (20025,'Mahangyo hiya hin pabor dinhi para kan Tessie.','He/She will ask for a favor here for Tessie.'),
  (20026,'Mahuram hiya hini nga kwarta para ha iyo pamilya.','He will borrow this money for your family.'),
  (20027,'Nagdara kami hin bukad didto para kan Alma.','We brought flowers there for Alma.'),
  (20028,'Nakaon an doktor hin tinapay didto ha tindahan.','The doctor is eating bread there (far) at the store.'),
  (20029,'Sinmaka hira didto ha balay ni Luz.','They climbed up there at Luz''s house.'),
  (20030,'Masugat ako han akon sangkay didto ha Gaisano.','I will catch up with my friend there (far) at Gaisano.'),
  (20031,'Akon ini nga balay.','This house is mine.'),
  (20032,'Imo an libro.','The book is yours (sing).'),
  (20033,'Iya an sapatos.','The shoes are his/hers.'),
  (20034,'Aton ini nga eskwelahan.','This school is ours (incl).'),
  (20035,'Amon an ayam.','The dog is ours (excl).'),
  (20036,'Iyo ini nga tsinelas.','These slippers are yours (pl).'),
  (20037,'Ira an sinehan.','The movie house is theirs.'),
  (20038,'Aton ini nga nasud.','This country is ours (incl).'),
  (20039,'Iya ini nga uma.','This farm is his.'),
  (20040,'Akon ini nga bata.','This baby is mine.'),
  (20041,'Inminom an akon uyab hin kape.','My boyfriend/girlfriend drank coffee.'),
  (20042,'Dinmala ako ha imo bag.','I brought your bag.'),
  (20043,'Peligroso an iya gugma.','His love is dangerous.'),
  (20044,'Adto an aton simbahan.','That (far) is our (incl) church.'),
  (20045,'Hinmulam hi Rico ha ámòn telebisyon.','Rico borrowed our television.'),
  (20046,'Makuyog hira Tata ngan Alex ha ịyo nga biyahe.','Tata and Alex will accompany (you) on your trip.'),
  (20047,'Maduroto an mga miyembro ha íra nga iglesiya.','The members of their church are industrious.'),
  (20048,'Imo ini nga gatas.','This milk is yours (sing).'),
  (20049,'Akon adto nga tsinelas.','That (far) slipper is mine.'),
  (20050,'Aton ini nga manok.','This chicken is ours (incl).'),
  (20051,'Kinmadto ako ha akon uma.','I went to my farm.'),
  (20052,'Binmisita hi Terso ha ịyo simbahan.','Terso visited your (pl) church.'),
  (20053,'Naupod an mga estudyante ha íra maestra.','The students accompanied their teacher.'),
  (20054,'Makaon ka han ámòn pagkaon.','You will eat our (excl) food.'),
  (20055,'Masugat hi Lucy han iya ayam didto ha siyudad.','Lucy will meet her dog there in the city.'),
  (20056,'Nahangyo hira hin pabor ha imo tatay.','They asked for a favor from your (sing) father.'),
  (20057,'Binmasa hi Rose han akon libro dida ha sala.','Rose read my book there in the living room.'),
  (20058,'Nakatawa hira ha imo nawong.','They laughed at your face.'),
  (20059,'Mahigda an akon anak ha imo katre.','My child will lay down (is going to lay down) on your bed.'),
  (20060,'Mapalit an akon maestra hini nga telebisyon para ha imo asawa.','My teacher will buy this television for your wife.'),
  (20061,'Inminom an mga panday hin kape didto ha íra balay.','The carpenters drank coffee there (far) at their house.'),
  (20062,'Ịyo ini nga leksyon.','This lesson is yours (pl).'),
  (20063,'Íra adto nga lamesa ngan lingkuranan.','That table and chair is theirs.'),
  (20064,'Kinmarawat hira kan Kristo ha íra kasingkásing.','They accepted Christ in (into) their hearts.'),
  (20065,'Matutdo hi Pastor Tan han Bibliya didto ha ịyo simbahan.','Pastor Tan will teach the Bible there (far) in your (pl) church.'),
  (20066,'Makanta an mga Kristiyano didto ha balay han áton kaharani.','The Christians will sing there at the house of our (pl) neighbors.'),
  (20067,'Nagdara an mga bisita hin pagkaon dinhi ha ámòn balay para ha Kaádlawan ni Ashley.','The visitors brought food (pl) here in our (pl) house for Ashley''s birthday.'),
  (20068,'Ira adto nga balay.','Their house over there.'),
  (20069,'Nadara hi Rose ha amon mga bado didto ha ira balay.','Rose brought our (excl) clothes there to their house.'),
  (20070,'Mabalhin an ira kaamyaw didto ha ira uma.','Their relatives will move there to their farm.'),
  (20071,'Iyo iton mga kabulig ha tindahan.','Those helpers in the store are yours (pl).'),
  (20072,'Pinmalit hiya hiton nga mangga dida ha imo sangkay.','He bought that mango from your (sing) friend.'),
  (20073,'Nanghuram an nars hin lapis ha iya nanay.','The nurse borrowed a pencil from her mother.'),
  (20074,'Aton ini nga mga bisita.','These visitors are ours (incl).'),
  (20075,'Upda an imo lola didto ha syudad.','Accompany (go with) your grandmother there (far) to the city.'),
  (20076,'Nahigda an iyo mga anak ha katre ni Katrina.','Your (pl) children laid down on Katrina''s bed.'),
  (20077,'Akon an pinirito nga manok.','The fried chicken is mine.'),
  (20078,'Matan-aw hiya ha akon.','He will look at me.'),
  (20079,'Makadto ako ha imo balay.','I will go to your house.'),
  (20080,'Hinmatag hi Perlita hin bola ha iya.','Perlita gave a ball to him.'),
  (20081,'Mabasa an akon anak hini nga libro ha amon.','My child will read this book to us (excl).'),
  (20082,'Nakanta hi Liling ha iyo.','Liling is singing to you (pl).'),
  (20083,'Pinmalit ako hin saging ha ira tindahan.','I bought banana at their store.'),
  (20084,'Pinmalit ako hin saging para ha ira.','I bought banana for them.'),
  (20085,'Mahuram hiya hin kwarta ha akon.','He will borrow money from me.'),
  (20086,'Maabot an iya bugto ha amon.','His/Her sibling will arrive to us (excl).'),
  (20087,'Mabisita hira Jun ngan Romy ha aton dinhi ha Davao.','Jun and Romy will visit us (incl) here in Davao.'),
  (20088,'Sinmurat an akon lolo ha ira didto ha states.','My grandfather wrote to them there in the states.'),
  (20089,'Naupod an amon anak ha ira.','Our (excl) child is going with them.'),
  (20090,'Daku an gugma ha Diyos para ha aton.','Great is God''s love for us (incl).'),
  (20091,'Mapipili ako ha ira.','I will choose from them.'),
  (20092,'Mahuhugasan an amon mga kabulig hin bado para ha iyo.','Our helpers will wash clothes for you (pl).'),
  (20093,'Makadto hi Alex ha iyo balay.','Alex will go to your (pl) house.'),
  (20094,'Masarig kita ha Iya, ngan mahatag Hiya hin bendisyon ha aton.','We will trust Him, and He will give a blessing to us (incl).'),
  (20095,'Mabalhin hira Jane ngan John ha amon balay.','Jane and John are moving to our (excl) house.'),
  (20096,'Kinmanta an uyab ni Lorie ha iya.','Lorie''s boyfriend sang to her.'),
  (20097,'Nagwali an pastor ha ira didto ha ira lugar.','The pastor preached to them there at their place.'),
  (20098,'Pinmalit an doktor hin saging ha amon tindahan.','The doctor bought bananas at our (excl) store.'),
  (20099,'Maampo an Pastor para ha akon ngan ha akon pamilya.','The Pastor will pray for me and my family.'),
  (20100,'Naupod ako ha iya.','I''m following with him.') on conflict (id) do nothing;

insert into lesson_blocks (id,lesson_id,ord,type,title,body_md,formula,drill_kind,drill_modality,drill_hint,drill_direction) values
  (20001,'pc-l1',1,'grammar','Personal Pronouns (I Class)','In Waray-Waray there are two kinds of pronouns:
1.  Personal Pronouns (I, you, we, my, your, etc.)
2.  General Pronouns (this, that, those, here, there, etc.)

### Personal Pronouns (I Class)
There are three classes of personal pronouns in Waray. These are called First Class (I), Second Class (II), and Third Class (III).

**1 Class Personal Pronouns**

| Singular | Meaning | Plural | Meaning |
| :------- | :------ | :----- | :------ |
| akó      | I       | kitá   | we (incl) |
| ikáw / ka | you     | kamí   | we (excl) |
| hiyá     | he/she  | kamó   | you (pl) |
|          |         | hira   | they    |

The personal pronoun `Ikaw` only has the short form which is `ka`. The personal pronoun `kita` is "inclusive", that is, it includes those to whom one is speaking; `kami` is "exclusive", that is, it excludes some or all.

A I Class Personal Pronoun marks the TOPIC of the sentence. The topic is the most important thing in the sentence. In English the speaker usually emphasizes particular words by saying it louder, or by his intonation or pitch. In Waray-Waray words in a sentence are given relative importance by "marking" them with a I Class word. Sometimes these I Class words are the subject of the sentence; at other times they are the object of the action, or the recipient or beneficiary of the action. The latter will be learned in a later lesson.

### Accent Marks
It will help as you hear Filipinos say new words to mark the accent, or stress. The accent is important in the Waray language. The standardized way of marking accents is as follows:
*   Accented syllable
*   Unaccented syllable w/ glottal stop
*   Accented syllable w/ glottal stop',null,null,null,null,null),
  (20002,'pc-l1',2,'examples',null,null,null,null,null,null,null),
  (20003,'pc-l1',3,'note',null,'`mga` is a pluralizer, indicating a plural form of the noun following.',null,null,null,null,null),
  (20004,'pc-l1',4,'note',null,'These Waray sentences are called equational sentences. There is no verb in these Waray sentences. The noun or adjective is "equated"(=) with the pronoun. The English translation uses the to be verb.',null,null,null,null,null),
  (20005,'pc-l1',5,'vocab',null,null,null,null,null,null,null),
  (20006,'pc-l1',6,'drill',null,null,null,'recognition','mc','peek',null),
  (20007,'pc-l1',7,'drill',null,null,null,'production','type','partial','both'),
  (20008,'pc-l2',1,'grammar','1 Class Markers','Just as there are three classes of personal pronouns in Waray-waray, there are also three classes of markers. A I Class Marker "marks" the TOPIC, or the emphasized word, of the sentence. Markers are used with proper nouns (people''s names) and common nouns.

| I Class Markers | w/ Proper Nouns | w/ Common Nouns |
| :-------------- | :-------------- | :-------------- |
| Singular        | Hi              | an              |
| Plural          | hira            | an mga          |',null,null,null,null,null),
  (20009,'pc-l2',2,'examples',null,null,null,null,null,null,null),
  (20010,'pc-l2',3,'note',null,'Ngan is a connector similar to the English conjunction and. Remember that mga indicates the noun which follows is plural. Like the previous lesson, these are equational sentences which do not need a verb. The English translation uses the to be verb.',null,null,null,null,null),
  (20011,'pc-l2',4,'vocab',null,null,null,null,null,null,null),
  (20012,'pc-l2',5,'drill',null,null,null,'recognition','mc','peek',null),
  (20013,'pc-l2',6,'drill',null,null,null,'production','type','partial','both'),
  (20014,'pc-l8',1,'examples',null,null,null,null,null,null,null),
  (20015,'pc-l8',2,'grammar','III Class Personal Pronouns Ma- Actor Focus','In the previous lesson, you learned how to add a beneficiary in a ma-actor focus using the III Class Markers kan and ha. The word para is also sometimes added. In this lesson you will learn how to use the III Class Personal Pronouns as a BENEFICIARY. These also function as a POSSESSOR. In their simplest form, they are as follows:

### III CLASS PERSONAL PRONOUNS

| SINGULAR | PLURAL      |
| :------- | :---------- |
| ákon     | áton (incl) |
| ímo      | ámòn (excl) |
| íya      | ịyo         |
|          | íra         |

The III Class Personal Pronouns have several variations as the following chart illustrates:

### III CLASS PERSONAL PRONOUN VARIATIONS

| I         | II          |
| :-------- | :---------- |
| ákon      | ha ákon     |
| ímo       | ha ímo      |
| íya       | ha íya      |
| áton(incl)| ha áton     |
| ámòn(excl)| ha ámòn     |
| ịyo       | ha ịyo      |
| íra       | ha íra      |

This may look very complicated to you right now, but once you understand how these pronouns are used in a sentence it will be easy. Actually, the form in column II is just a variation of the "real" pronouns in column I.

For example, look at the pronoun akon in column I. Notice the difference in each column:

| akon         | ha akon                                    |
| :----------- | :----------------------------------------- |
| root pronoun | ha + root                                  |
| "mine"     | "to (at, for, with) me" /"to (at, for, with) my..." |

In this lesson you will learn how to use the pronoun in column I. This is the one will used to show POSSESSION. In the next lesson you will learn how to use the form in column II which show the beneficiary.

Akon also means "my" (possessor). Thus it is possible to show possession in the following ways:
*   Ini an lapis nakon. (This is my pencil.)
*   Ini an akon lapis. (This is my pencil.)

Either way is acceptable, but the last is more common. Notice that the II Class nakon always follows the noun, while the III Class akon always precedes the noun as in the following examples:
*   akon uyab - my girlfriend
*   imo ngaran - your (sing) name
*   iya lawas - his body
*   aton Diyos - our (incl) God
*   ámòn apoy - our (excl) grandmother
*   ịyo uma - your (pl) farm
*   íra kaharani - their neighbor

The following examples demonstrate how this possessive pronoun is used in a ma-actor focus sentence:',null,null,null,null,null),
  (20016,'pc-l8',3,'examples',null,null,null,null,null,null,null),
  (20017,'pc-l8',4,'examples',null,null,null,null,null,null,null),
  (20018,'pc-l8',5,'examples',null,null,null,null,null,null,null),
  (20019,'pc-l8',6,'vocab',null,null,null,null,null,null,null),
  (20020,'pc-l8',7,'drill',null,null,null,'recognition','mc','peek',null),
  (20021,'pc-l8',8,'drill',null,null,null,'production','type','partial','both'),
  (20022,'pc-l9',1,'examples',null,null,null,null,null,null,null),
  (20023,'pc-l9',2,'grammar','II Class Personal Pronouns (cont.)','In lesson 8 you learned how to use the III Class Personal Pronouns below in column I. These pronouns are used to show possession. In this lesson you will learn how to use the pronouns in column II. These pronouns show the BENEFICIARY or the DIRECTION of the action of the verb. The pronouns in column II are formed by adding `ha` before the root pronouns and are used opposite to the III Class pronoun.

### III CLASS PERSONAL PRONOUN VARIATIONS

| I           | II        |
| :---------- | :-------- |
| akon        | Ha akon   |
| imo         | Ha imo    |
| iya         | Ha iya    |
| aton (incl) | Ha aton   |
| amon (excl) | Ha amon   |
| iyo         | Ha iyo    |
| ira         | Ha ira    |

`ha akon` (column II) - "to (at, with, from) me" / "to (at, with, from) my..."

These III Class Pronouns show the beneficiary or the direction of the action of the verb.',null,null,null,null,null),
  (20024,'pc-l9',3,'examples',null,null,null,null,null,null,null),
  (20025,'pc-l9',4,'examples',null,null,null,null,null,null,null),
  (20026,'pc-l9',5,'vocab',null,null,null,null,null,null,null),
  (20027,'pc-l9',6,'drill',null,null,null,'recognition','mc','peek',null),
  (20028,'pc-l9',7,'drill',null,null,null,'production','type','partial','both') on conflict (id) do nothing;

insert into block_items (block_id,ord,dict_waray,expr_id,role) values
  (20002,1,null,20001,'example'),
  (20002,2,null,20002,'example'),
  (20002,3,null,20003,'example'),
  (20002,4,null,20004,'example'),
  (20002,5,null,20005,'example'),
  (20002,6,null,20006,'example'),
  (20002,7,null,20007,'example'),
  (20002,8,null,20008,'example'),
  (20002,9,null,20009,'example'),
  (20002,10,null,20010,'example'),
  (20005,1,'Tátay',null,'teach'),
  (20005,2,'Amerikáno',null,'teach'),
  (20005,3,'Asáwa',null,'teach'),
  (20005,4,'Babáye',null,'teach'),
  (20005,5,'Buótan',null,'teach'),
  (20005,6,'Riko',null,'teach'),
  (20005,7,'Estudyánte',null,'teach'),
  (20005,8,'Mahúsay',null,'teach'),
  (20005,9,'Gwápo',null,'teach'),
  (20005,10,'Sángkay',null,'teach'),
  (20005,11,'Nánay',null,'teach'),
  (20005,12,'mapasô',null,'teach'),
  (20005,13,'Kristohánon',null,'teach'),
  (20005,14,'maduróto',null,'teach'),
  (20005,15,'makusóg',null,'teach'),
  (20005,16,'laláke',null,'teach'),
  (20005,17,'maéstro',null,'teach'),
  (20005,18,'Misyonaryo',null,'teach'),
  (20005,19,'Pilipíno',null,'teach'),
  (20005,20,'Hataás',null,'teach'),
  (20005,21,'Matámbok',null,'teach'),
  (20005,22,'mga',null,'teach'),
  (20006,1,'Tátay',null,'item'),
  (20006,2,'Amerikáno',null,'item'),
  (20006,3,'Asáwa',null,'item'),
  (20006,4,'Babáye',null,'item'),
  (20006,5,'Buótan',null,'item'),
  (20006,6,'Riko',null,'item'),
  (20006,7,'Estudyánte',null,'item'),
  (20006,8,'Mahúsay',null,'item'),
  (20007,1,'Tátay',null,'item'),
  (20007,2,'Amerikáno',null,'item'),
  (20007,3,'Asáwa',null,'item'),
  (20007,4,'Babáye',null,'item'),
  (20007,5,'Buótan',null,'item'),
  (20007,6,'Riko',null,'item'),
  (20007,7,'Estudyánte',null,'item'),
  (20007,8,'Mahúsay',null,'item'),
  (20009,1,null,20011,'example'),
  (20009,2,null,20012,'example'),
  (20009,3,null,20013,'example'),
  (20009,4,null,20014,'example'),
  (20009,5,null,20015,'example'),
  (20009,6,null,20016,'example'),
  (20009,7,null,20017,'example'),
  (20009,8,null,20018,'example'),
  (20009,9,null,20019,'example'),
  (20009,10,null,20020,'example'),
  (20011,1,'Lingkúran',null,'teach'),
  (20011,2,'Báso',null,'teach'),
  (20011,3,'Bátà',null,'teach'),
  (20011,4,'Bóla',null,'teach'),
  (20011,5,'Malabad',null,'teach'),
  (20011,6,'Dakú',null,'teach'),
  (20011,7,'Gutiay',null,'teach'),
  (20011,8,'Kláse',null,'teach'),
  (20011,9,'Lamésa',null,'teach'),
  (20011,10,'Léksyon',null,'teach'),
  (20011,11,'madíg-on',null,'teach'),
  (20011,12,'malídong',null,'teach'),
  (20011,13,'makuri',null,'teach'),
  (20011,14,'maúpay',null,'teach'),
  (20011,15,'mahúsay',null,'teach'),
  (20011,16,'Papél',null,'teach'),
  (20011,17,'Punô',null,'teach'),
  (20011,18,'Mabuság',null,'teach'),
  (20011,19,'masayón',null,'teach'),
  (20012,1,'Lingkúran',null,'item'),
  (20012,2,'Báso',null,'item'),
  (20012,3,'Bátà',null,'item'),
  (20012,4,'Bóla',null,'item'),
  (20012,5,'Malabad',null,'item'),
  (20012,6,'Dakú',null,'item'),
  (20012,7,'Gutiay',null,'item'),
  (20012,8,'Kláse',null,'item'),
  (20013,1,'Lingkúran',null,'item'),
  (20013,2,'Báso',null,'item'),
  (20013,3,'Bátà',null,'item'),
  (20013,4,'Bóla',null,'item'),
  (20013,5,'Malabad',null,'item'),
  (20013,6,'Dakú',null,'item'),
  (20013,7,'Gutiay',null,'item'),
  (20013,8,'Kláse',null,'item'),
  (20014,1,null,20021,'example'),
  (20014,2,null,20022,'example'),
  (20014,3,null,20023,'example'),
  (20014,4,null,20024,'example'),
  (20014,5,null,20025,'example'),
  (20014,6,null,20026,'example'),
  (20014,7,null,20027,'example'),
  (20014,8,null,20028,'example'),
  (20014,9,null,20029,'example'),
  (20014,10,null,20030,'example'),
  (20016,1,null,20031,'example'),
  (20016,2,null,20032,'example'),
  (20016,3,null,20033,'example'),
  (20016,4,null,20034,'example'),
  (20016,5,null,20035,'example'),
  (20016,6,null,20036,'example'),
  (20016,7,null,20037,'example'),
  (20016,8,null,20038,'example'),
  (20016,9,null,20039,'example'),
  (20016,10,null,20040,'example'),
  (20017,1,null,20041,'example'),
  (20017,2,null,20042,'example'),
  (20017,3,null,20043,'example'),
  (20017,4,null,20044,'example'),
  (20017,5,null,20045,'example'),
  (20017,6,null,20046,'example'),
  (20017,7,null,20047,'example'),
  (20018,1,null,20048,'example'),
  (20018,2,null,20049,'example'),
  (20018,3,null,20050,'example'),
  (20018,4,null,20051,'example'),
  (20018,5,null,20052,'example'),
  (20018,6,null,20053,'example'),
  (20018,7,null,20054,'example'),
  (20018,8,null,20055,'example'),
  (20018,9,null,20056,'example'),
  (20018,10,null,20057,'example'),
  (20018,11,null,20058,'example'),
  (20018,12,null,20059,'example'),
  (20018,13,null,20060,'example'),
  (20018,14,null,20061,'example'),
  (20018,15,null,20062,'example'),
  (20018,16,null,20063,'example'),
  (20018,17,null,20064,'example'),
  (20018,18,null,20065,'example'),
  (20018,19,null,20066,'example'),
  (20018,20,null,20067,'example'),
  (20019,1,'-bisíta',null,'teach'),
  (20019,2,'bisita',null,'teach'),
  (20019,3,'biyáhe',null,'teach'),
  (20019,4,'Diyós',null,'teach'),
  (20019,5,'gúgma',null,'teach'),
  (20019,6,'-higdà',null,'teach'),
  (20019,7,'iglésiya',null,'teach'),
  (20019,8,'Kaádlawan',null,'teach'),
  (20019,9,'kasingkásing',null,'teach'),
  (20019,10,'kátre',null,'teach'),
  (20019,11,'láwas',null,'teach'),
  (20019,12,'manók',null,'teach'),
  (20019,13,'násud',null,'teach'),
  (20019,14,'nawóng',null,'teach'),
  (20019,15,'ngáran',null,'teach'),
  (20019,16,'-upód',null,'teach'),
  (20019,17,'pagkáon',null,'teach'),
  (20019,18,'-karáwat',null,'teach'),
  (20019,19,'-súgat',null,'teach'),
  (20019,20,'peligróso',null,'teach'),
  (20019,21,'sinehán',null,'teach'),
  (20019,22,'siyudád',null,'teach'),
  (20019,23,'telebisyon',null,'teach'),
  (20019,24,'-tútdò',null,'teach'),
  (20019,25,'umá',null,'teach'),
  (20020,1,'-bisíta',null,'item'),
  (20020,2,'bisita',null,'item'),
  (20020,3,'biyáhe',null,'item'),
  (20020,4,'Diyós',null,'item'),
  (20020,5,'gúgma',null,'item'),
  (20020,6,'-higdà',null,'item'),
  (20020,7,'iglésiya',null,'item'),
  (20020,8,'Kaádlawan',null,'item'),
  (20021,1,'-bisíta',null,'item'),
  (20021,2,'bisita',null,'item'),
  (20021,3,'biyáhe',null,'item'),
  (20021,4,'Diyós',null,'item'),
  (20021,5,'gúgma',null,'item'),
  (20021,6,'-higdà',null,'item'),
  (20021,7,'iglésiya',null,'item'),
  (20021,8,'Kaádlawan',null,'item'),
  (20022,1,null,20068,'example'),
  (20022,2,null,20069,'example'),
  (20022,3,null,20070,'example'),
  (20022,4,null,20071,'example'),
  (20022,5,null,20072,'example'),
  (20022,6,null,20073,'example'),
  (20022,7,null,20074,'example'),
  (20022,8,null,20075,'example'),
  (20022,9,null,20076,'example'),
  (20022,10,null,20077,'example'),
  (20024,1,null,20078,'example'),
  (20024,2,null,20079,'example'),
  (20024,3,null,20080,'example'),
  (20024,4,null,20081,'example'),
  (20024,5,null,20082,'example'),
  (20024,6,null,20083,'example'),
  (20024,7,null,20084,'example'),
  (20024,8,null,20085,'example'),
  (20025,1,null,20086,'example'),
  (20025,2,null,20087,'example'),
  (20025,3,null,20088,'example'),
  (20025,4,null,20089,'example'),
  (20025,5,null,20090,'example'),
  (20025,6,null,20091,'example'),
  (20025,7,null,20092,'example'),
  (20025,8,null,20093,'example'),
  (20025,9,null,20094,'example'),
  (20025,10,null,20095,'example'),
  (20025,11,null,20096,'example'),
  (20025,12,null,20097,'example'),
  (20025,13,null,20098,'example'),
  (20025,14,null,20099,'example'),
  (20025,15,null,20100,'example'),
  (20026,1,'abót',null,'teach'),
  (20026,2,'ámpo',null,'teach'),
  (20026,3,'bendisyon',null,'teach'),
  (20026,4,'búgtò',null,'teach'),
  (20026,5,'hátag',null,'teach'),
  (20026,6,'lugár',null,'teach'),
  (20026,7,'píli',null,'teach'),
  (20026,8,'sárig',null,'teach'),
  (20026,9,'surát',null,'teach'),
  (20026,10,'siring',null,'teach'),
  (20026,11,'upod',null,'teach'),
  (20026,12,'wáli',null,'teach'),
  (20027,1,'abót',null,'item'),
  (20027,2,'ámpo',null,'item'),
  (20027,3,'bendisyon',null,'item'),
  (20027,4,'búgtò',null,'item'),
  (20027,5,'hátag',null,'item'),
  (20027,6,'lugár',null,'item'),
  (20027,7,'píli',null,'item'),
  (20027,8,'sárig',null,'item'),
  (20028,1,'abót',null,'item'),
  (20028,2,'ámpo',null,'item'),
  (20028,3,'bendisyon',null,'item'),
  (20028,4,'búgtò',null,'item'),
  (20028,5,'hátag',null,'item'),
  (20028,6,'lugár',null,'item'),
  (20028,7,'píli',null,'item'),
  (20028,8,'sárig',null,'item');
