/* Waray vocabulary — shared by every Waray course model (Classic, Frequency).
   Rows: [deck, waray, english, subtext, respelling]. Card ids are positional
   (c0, c1, …) — APPEND ONLY; never insert or reorder existing rows. */
export const SEED = [
  // ---- Greetings & survival (from teacher dialogues + common usage) ----
  ["greet", "Maupay nga aga", "Good morning", "", "mah-OO-pigh ngah AH-gah"],
  ["greet", "Maupay nga kulop", "Good afternoon", "", "mah-OO-pigh ngah KOO-lop"],
  ["greet", "Maupay nga gab-i", "Good evening / Good night", "the - in gab-i is a glottal stop", "mah-OO-pigh ngah gahb-EE"],
  ["greet", "Kumusta ka?", "How are you?", "", "koo-moos-TAH kah"],
  ["greet", "Maupay man", "I'm good / fine (so far)", "", "mah-OO-pigh mahn"],
  ["greet", "Salamat", "Thank you", "", "sah-LAH-mat"],
  ["greet", "Damo nga salamat", "Thank you very much", "", "DAH-mo ngah sah-LAH-mat"],
  ["greet", "Oo", "Yes", "", "AW-aw"],
  ["greet", "Diri", "No / not", "used for present & future answers", "DEE-ree"],
  ["greet", "Waray", "None / nothing", "also 'no' for past-tense answers; and the language's name", "wah-RIGH"],
  ["greet", "Waray pa", "Not yet", "", "wah-RIGH pah"],
  ["greet", "Anay", "Wait / just a moment", "", "AH-nigh"],
  ["greet", "Pasensya na", "Sorry / excuse me", "", "pah-SEN-syah nah"],
  ["greet", "Sige", "Okay / go ahead", "", "SEE-geh"],
  ["greet", "Adi", "Here it is", "", "AH-dee"],
  ["greet", "Pwede", "Can / may (I)", "", "PWEH-deh"],
  ["greet", "Naintindihan ko", "I understand", "", "nah-een-tin-dee-HAHN ko"],
  ["greet", "Diri ako maaram", "I don't know", "", "DEE-ree ah-KAW mah-AH-ram"],
  ["greet", "Karuyag ko", "I want", "", "kah-ROO-yag ko"],

  // ---- Week 1 — foundations ----
  ["week1", "Nakikit-an mo?", "Can you see it?", "", "nah-kee-KEET-an mo"],
  ["week1", "Oo, nakikit-an ko", "Yes, I can see it", "", "AW-aw nah-kee-KEET-an ko"],
  ["week1", "Klaro?", "Is it clear?", "", "KLAH-ro"],
  ["week1", "Oo, klaro", "Yes, it's clear", "", "AW-aw KLAH-ro"],
  ["week1", "Diri klaro", "No, it's not clear", "", "DEE-ree KLAH-ro"],
  ["week1", "Naintindihan nimo?", "Do you understand?", "", "nah-een-tin-dee-HAHN NEE-mo"],
  ["week1", "Oo, naintindihan ko", "Yes, I understand", "", "AW-aw nah-een-tin-dee-HAHN ko"],
  ["week1", "Taga diin ka?", "Where are you from?", "", "TAH-gah dee-EEN kah"],
  ["week1", "Hain ka?", "Where are you?", "", "HAH-een kah"],
  ["week1", "ako", "I", "subject pronoun", "ah-KAW"],
  ["week1", "ikaw / ka", "you", "ka is the short form", "ee-KOW / kah"],
  ["week1", "kita", "we (inclusive)", "includes the person you're talking to", "kee-TAH"],
  ["week1", "kami", "we (exclusive)", "excludes the listener", "kah-MEE"],
  ["week1", "hiya", "he / she", "no gender marking", "HEE-yah"],
  ["week1", "kamo", "you / y'all", "plural you", "kah-MAW"],
  ["week1", "hira", "they", "", "HEE-rah"],
  ["week1", "Kaon kita", "Let's eat", "", "KAH-on kee-TAH"],
  ["week1", "Kumaon kita", "We ate", "pangaon = food; kumaon = the act of eating", "koo-MAH-on kee-TAH"],
  ["week1", "Mahusay ka", "You are beautiful", "", "mah-hoo-SIGH kah"],
  ["week1", "Maraksot ka", "You are ugly", "", "mah-RAK-sot kah"],
  ["week1", "Ano imo gin-hihimo?", "What are you doing?", "", "AH-no EE-mo gin-hee-HEE-mo"],
  ["week1", "Ano imo gin-kakaon?", "What are you eating?", "", "AH-no EE-mo gin-kah-KAH-on"],
  ["week1", "tatay", "father", "", "TAH-tigh"],
  ["week1", "nanay", "mother", "", "NAH-nigh"],
  ["week1", "Amerikano", "American (male)", "", "ah-meh-ree-KAH-no"],
  ["week1", "turista", "tourist", "", "too-REES-tah"],
  ["week1", "babaye", "woman", "syllables: ba-ba-ye", "bah-BAH-yeh"],
  ["week1", "malipay", "happy", "", "mah-LEE-pigh"],
  ["week1", "buoton", "nice / kind / good", "also written bouton", "boo-OH-ton"],
  ["week1", "makusog", "strong", "", "mah-KOO-sog"],
  ["week1", "riko", "rich", "", "REE-ko"],
  ["week1", "lalaki", "man", "", "lah-LAH-kee"],
  ["week1", "asawa", "wife / spouse", "", "ah-SAH-wah"],
  ["week1", "mapaso", "hot", "", "mah-PAH-so"],
  ["week1", "bisita", "visitor", "", "bee-SEE-tah"],
  ["week1", "Pilipino", "Filipino (male)", "", "pee-lee-PEE-no"],
  ["week1", "gwapo", "handsome", "", "GWAH-po"],
  ["week1", "sangkay", "friend", "", "sahng-KIGH"],
  ["week1", "hataas", "tall / long", "", "hah-TAH-as"],
  ["week1", "matambok", "fat", "", "mah-TAM-bok"],
  ["week1", "estudyante", "student", "", "es-tood-YAHN-teh"],
  ["week1", "maestro / maestra", "teacher (m / f)", "", "mah-ES-tro / mah-ES-trah"],
  ["week1", "Estudyante kami", "We (excl.) are students", "", "es-tood-YAHN-teh kah-MEE"],
  ["week1", "Pilipino hira", "They are Filipinos", "", "pee-lee-PEE-no HEE-rah"],
  ["week1", "Babaye ka", "You are a woman", "", "bah-BAH-yeh kah"],
  ["week1", "Amerikano ako", "I am American", "", "ah-meh-ree-KAH-no ah-KAW"],
  ["week1", "Makusog ka", "You are strong", "", "mah-KOO-sog kah"],
  ["week1", "Turista hiya", "She is a tourist", "", "too-REES-tah HEE-yah"],
  ["week1", "Maestra kami", "We (excl.) are teachers", "", "mah-ES-trah kah-MEE"],
  ["week1", "Makusog hiya", "He is strong", "", "mah-KOO-sog HEE-yah"],
  ["week1", "Bisita hira", "They are visitors", "", "bee-SEE-tah HEE-rah"],
  ["week1", "Nanay ako", "I am a mother", "", "NAH-nigh ah-KAW"],
  ["week1", "Hinay-hinay la", "Just slowly, please", "", "HEE-nigh HEE-nigh lah"],
  ["week1", "Pakpak anay", "Clap first", "", "PAK-pak AH-nigh"],
  ["week1", "Makarit ka", "You are excellent", "", "mah-KAH-rit kah"],
  ["week1", "kay", "because", "", "kigh"],

  // ---- Verbs, objects & time ----
  ["verbs", "Mag-aano ka?", "What are you going to do?", "", "mahg-AH-ah-no kah"],
  ["verbs", "baktas", "to walk", "magbaktas = to walk/go on foot", "BAK-tas"],
  ["verbs", "karsada", "road", "", "kar-SAH-dah"],
  ["verbs", "bukid", "mountain", "", "BOO-kid"],
  ["verbs", "laba", "to wash (clothes)", "", "LAH-bah"],
  ["verbs", "bado", "clothes", "", "BAH-do"],
  ["verbs", "panyo", "handkerchief", "", "PAHN-yo"],
  ["verbs", "mantel", "tablecloth", "", "man-TEL"],
  ["verbs", "biray", "curtain", "", "bee-RIGH"],
  ["verbs", "sapatos", "shoes", "", "sah-PAH-tos"],
  ["verbs", "taklap", "blanket", "", "TAK-lap"],
  ["verbs", "hugas", "to wash (dishes)", "", "HOO-gas"],
  ["verbs", "tinidor", "fork", "", "tee-nee-DOR"],
  ["verbs", "kutsara", "spoon", "", "koot-SAH-rah"],
  ["verbs", "pinggan", "plate", "", "PING-gan"],
  ["verbs", "baso", "glass", "", "BAH-so"],
  ["verbs", "sarakyan", "vehicle", "", "sah-RAK-yan"],
  ["verbs", "motor", "motorcycle", "", "mo-TOR"],
  ["verbs", "limpyu", "to clean", "", "LIM-pyoo"],
  ["verbs", "awto", "car / auto", "", "OW-to"],
  ["verbs", "kwarto", "room", "", "KWAR-to"],
  ["verbs", "banyo", "bathroom", "", "BAHN-yo"],
  ["verbs", "balay", "house", "", "bah-LIGH"],
  ["verbs", "kusina", "kitchen", "", "koo-SEE-nah"],
  ["verbs", "luto", "to cook", "", "LOO-to"],
  ["verbs", "isda", "fish", "", "ees-DAH"],
  ["verbs", "manok", "chicken", "", "mah-NOK"],
  ["verbs", "karne", "meat", "", "KAR-neh"],
  ["verbs", "utan", "vegetable", "", "OO-tan"],
  ["verbs", "saribo", "to water plants", "", "sah-REE-bo"],
  ["verbs", "tanom", "plant", "", "TAH-nom"],
  ["verbs", "lukot", "to fold (clothes)", "", "LOO-kot"],
  ["verbs", "tago", "to hide", "", "TAH-go"],
  ["verbs", "andam", "to get ready", "", "AN-dam"],
  ["verbs", "basa", "to read", "", "BAH-sah"],
  ["verbs", "sudlay", "to comb", "", "sood-LIGH"],
  ["verbs", "sayaw", "to dance", "", "sah-YOW"],
  ["verbs", "maneho", "to drive", "", "mah-NEH-ho"],
  ["verbs", "Mag- + verb", "future tense (actor focus)", "e.g. magbabaktas = will walk", "mahg"],
  ["verbs", "Nag- + verb", "present / past tense", "naglalaba = washing; naglaba = washed", "nahg"],
  ["verbs", "Pag- + verb", "command form", "paglaba = wash!", "pahg"],
  ["verbs", "yana", "now", "", "YAH-nah"],
  ["verbs", "niyan", "later", "", "nee-YAN"],
  ["verbs", "buwas", "tomorrow", "", "BOO-was"],
  ["verbs", "kakulop", "yesterday", "", "kah-KOO-lop"],
  ["verbs", "kanina han aga", "earlier this morning", "", "kah-NEE-nah hahn AH-gah"],
  ["verbs", "yana nga aga", "this morning (now)", "", "YAH-nah ngah AH-gah"],
  ["verbs", "kulop", "afternoon", "", "KOO-lop"],
  ["verbs", "yana nga gab-i", "tonight", "", "YAH-nah ngah gahb-EE"],
  ["verbs", "kagab-i", "last night", "", "kah-gahb-EE"],
  ["verbs", "kanina", "a little while ago", "", "kah-NEE-nah"],
  ["verbs", "didi", "here", "", "DEE-dee"],
  ["verbs", "dida", "there", "", "DEE-dah"],
  ["verbs", "Ano it oras dida?", "What time is it there?", "", "AH-no eet OH-ras DEE-dah"],
  ["verbs", "Alas singko didi", "It's 5 o'clock here", "Spanish-style clock times", "AH-las SEENG-ko DEE-dee"],
  ["verbs", "uran / mauran", "rain / rainy", "", "OO-ran / mah-OO-ran"],
  ["verbs", "mapaso hin duro", "very hot", "", "mah-PAH-so heen DOO-ro"],
  ["verbs", "matugnaw", "cold", "", "mah-TOOG-now"],
  ["verbs", "sirak / masirak", "sun ray / sunny", "", "SEE-rak / mah-SEE-rak"],
  ["verbs", "dampog / madampog", "clouds / cloudy", "", "DAM-pog / mah-DAM-pog"],
  ["verbs", "hangin / mahangin", "wind / windy", "", "HAH-ngin / mah-HAH-ngin"],
  ["verbs", "may bagyo", "there is a storm", "", "migh BAHG-yo"],
  ["verbs", "Kumusta it panahon?", "How is the weather?", "", "koo-moos-TAH eet pah-nah-HON"],

  // ---- Phrases — invitations (Sheet 3) ----
  ["invite", "imbitasyon", "invitation", "", "im-bee-tah-SYON"],
  ["invite", "may / mayda", "there is / I have", "", "migh / MIGH-dah"],
  ["invite", "gin-iimbita", "being invited", "", "gin-ee-im-BEE-tah"],
  ["invite", "May libre ka ba nga oras hit Sabado?", "Do you have free time on Saturday?", "", "migh LEE-breh kah bah ngah OH-ras heet sah-BAH-do"],
  ["invite", "Ano it mayda?", "What's going on?", "", "AH-no eet MIGH-dah"],
  ["invite", "Nag-arog ako", "I prepared food", "", "nag-AH-rog ah-KAW"],
  ["invite", "Mayda pangaon ha balay", "There is food at home", "", "MIGH-dah pah-NGAH-on hah bah-LIGH"],
  ["invite", "Ano nga oras?", "What time?", "", "AH-no ngah OH-ras"],
  ["invite", "Alas sais ha gab-i", "At 6 in the evening", "", "AH-las SAH-ees hah gahb-EE"],
  ["invite", "Poydi ko ba ig-upod hi Rey?", "Can I bring Rey along?", "", "POY-dee ko bah eeg-OO-pod hee RAY"],
  ["invite", "ig-upod", "to bring along", "", "eeg-OO-pod"],
  ["invite", "akon patod", "my cousin", "", "AH-kon PAH-tod"],
  ["invite", "makadto", "will go to", "", "mah-KAD-to"],
  ["invite", "Siyempre, poydi", "Of course, you can", "", "see-YEM-preh POY-dee"],
  ["invite", "Maghuhulat ako ha iyo", "I will wait for you all", "", "mag-hoo-HOO-lat ah-KAW hah EE-yo"],
  ["invite", "hulat", "to wait", "", "HOO-lat"],
  ["invite", "Sigurado, makadto kami", "Sure, we'll come", "", "see-goo-RAH-do mah-KAD-to kah-MEE"],
  ["invite", "Sige, magkita kita hit Sabado", "Okay, let's meet on Saturday", "", "SEE-geh mag-KEE-tah kee-TAH heet sah-BAH-do"],
  ["invite", "magkita", "to meet", "", "mag-KEE-tah"],

  // ---- appended: standalone adjectives (kept at the end so existing card ids,
  //      which are positional c{index}, don't shift and break saved progress) ----
  ["week1", "mahusay", "beautiful", "", "mah-hoo-SIGH"],
  ["week1", "maraksot", "ugly", "", "mah-RAK-sot"],
  ["week1", "makarit", "excellent", "", "mah-KAH-rit"],

  // ===== Out & About — Directions (from Pagpakiana…Direksiyon) =====
  ["direk", "bangko", "bank", "", "BANG-ko"],
  ["direk", "botika", "pharmacy", "", "bo-TEE-kah"],
  ["direk", "ospital", "hospital", "", "os-pee-TAL"],
  ["direk", "istasyon hit pulis", "police station", "", "ees-tah-SYON heet poo-LEES"],
  ["direk", "munisipyo", "town / city hall", "", "moo-nee-SEEP-yo"],
  ["direk", "paradahan", "terminal", "where vehicles wait", "pah-rah-DAH-han"],
  ["direk", "eskina", "corner", "", "es-KEE-nah"],
  ["direk", "atbang", "across / in front of", "", "AT-bang"],
  ["direk", "dinhi", "here", "like didi", "DEEN-hee"],
  ["direk", "harani", "near", "", "hah-RAH-nee"],
  ["direk", "harayo", "far", "", "hah-RAH-yo"],
  ["direk", "bus", "bus", "", "boos"],
  ["direk", "dyip", "jeepney", "", "jeep"],
  ["direk", "taxi", "taxi", "", "TAK-see"],
  ["direk", "pedicab", "pedicab", "bicycle with sidecar", "PEH-dee-kab"],
  ["direk", "traysikol", "tricycle", "motorbike with sidecar", "trigh-SEE-kol"],
  ["direk", "Pwede magpakiana?", "May I ask a question?", "", "PWEH-deh mag-pah-kee-AH-na"],
  ["direk", "Hain it bangko?", "Where is the bank?", "hain = where", "HAH-een eet BANG-ko"],
  ["direk", "Harayo ba tikang dinhi?", "Is it far from here?", "", "hah-RAH-yo bah TEE-kang DEEN-hee"],
  ["direk", "Waray sapayan", "You're welcome", "lit. no problem", "wah-RIGH sah-PAH-yan"],
  ["direk", "Harani la", "It's just near", "", "hah-RAH-nee lah"],
  ["direk", "Pwede baktason", "It can be walked", "", "PWEH-deh bak-TAH-son"],
  ["direk", "Ika-upat nga eskina tikang dinhi", "The 4th corner from here", "", "ee-kah-OO-pat ngah es-KEE-nah TEE-kang DEEN-hee"],
  ["direk", "Pagbus nala", "Just take the bus", "", "pag-BOOS nah-lah"],

  // ===== Out & About — Shopping (from Useful_Words_When_Buying_Things) =====
  ["shop", "tindahan", "store", "", "teen-DAH-han"],
  ["shop", "tindera", "vendor", "shopkeeper", "teen-DEH-rah"],
  ["shop", "kahera", "cashier", "", "kah-HEH-rah"],
  ["shop", "kwarta", "money", "", "KWAR-tah"],
  ["shop", "sukli", "change", "money returned", "sook-LEE"],
  ["shop", "sinsilyo", "coins", "", "seen-SEEL-yo"],
  ["shop", "barato", "cheap", "", "bah-RAH-to"],
  ["shop", "bulad", "dried fish", "", "BOO-lad"],
  ["shop", "tinapa", "smoked fish", "", "tee-NAH-pah"],
  ["shop", "palit", "to buy", "papaliton = will buy", "PAH-leet"],
  ["shop", "ginbibiling", "looking for", "from biling", "gin-bee-BEE-ling"],
  ["shop", "karuyag", "want / like", "also gusto", "kah-ROO-yag"],
  ["shop", "baraydan", "amount to pay", "", "bah-RIGH-dan"],
  ["shop", "bulig", "to help", "buligan = help someone", "BOO-leeg"],
  ["shop", "Ano ini?", "What is this?", "", "AH-no ee-NEE"],
  ["shop", "Tagpira ini?", "How much is this?", "", "tag-PEE-rah ee-NEE"],
  ["shop", "Hain tungod it kahera?", "Where is the cashier?", "hain tungod = where located", "HAH-een TOO-ngod eet kah-HEH-rah"],
  ["shop", "May tinapa kamo dinhi?", "Do you have smoked fish here?", "", "migh tee-NAH-pah kah-MAW DEEN-hee"],
  ["shop", "Ini it akon papaliton", "This is what I'll buy", "", "ee-NEE eet AH-kon pah-pah-LEE-ton"],
  ["shop", "Pwede mo ako buligan?", "Can you help me?", "", "PWEH-deh mo ah-KAW boo-LEE-gan"],
  ["shop", "Hain it mas barato?", "Which one is cheaper?", "", "HAH-een eet mahs bah-RAH-to"],
  ["shop", "Adi it imo sukli", "Here is your change", "", "AH-dee eet EE-mo sook-LEE"],
  ["shop", "Pira it akon baraydan?", "How much do I pay?", "", "PEE-rah eet AH-kon bah-RIGH-dan"],

  // ===== Out & About — At the airport (from Ha_Airport) =====
  ["airport", "eroplano", "airplane", "", "eh-ro-PLAH-no"],
  ["airport", "tiket", "ticket", "", "TEE-ket"],
  ["airport", "bagahe", "baggage", "", "bah-GAH-heh"],
  ["airport", "gate", "gate", "", "gayt"],
  ["airport", "kostums", "customs", "", "KOS-tooms"],
  ["airport", "pasaporte", "passport", "", "pah-sah-POR-teh"],
  ["airport", "pasahero", "passenger", "", "pah-sah-HEH-ro"],
  ["airport", "Pakitaa ako hit imo tiket", "Please show me your ticket", "pakitaa = let me see", "pah-kee-tah-AH ah-KAW heet EE-mo TEE-ket"],
  ["airport", "Pakitaa ako hit imo pasaporte", "Please show me your passport", "", "pah-kee-tah-AH ah-KAW heet EE-mo pah-sah-POR-teh"],
  ["airport", "Malupad it eroplano alas nuybe", "The plane leaves at 9", "malupad = will fly", "mah-LOO-pad eet eh-ro-PLAH-no AH-las NOOY-beh"],
  ["airport", "Deritso ha gate numero dos", "Straight to gate number 2", "", "deh-REET-so hah gayt NOO-meh-ro dos"],
  ["airport", "Enjoy hit imo biyahe", "Enjoy your trip", "", "en-JOY heet EE-mo bee-YAH-heh"],

  // ===== Out & About — A day trip (from PPERFECT_pamasyada_Kita) =====
  ["daytrip", "pamasyada", "outing / stroll", "sightseeing", "pah-mas-YAH-dah"],
  ["daytrip", "tulay", "bridge", "", "too-LIGH"],
  ["daytrip", "lugar", "place", "", "loo-GAR"],
  ["daytrip", "isla", "island", "", "EES-lah"],
  ["daytrip", "museo", "museum", "", "moo-SEH-o"],
  ["daytrip", "pumpboat", "pump boat", "motorized outrigger", "POMP-bot"],
  ["daytrip", "makaradlok", "scary", "", "mah-kah-RAD-lok"],
  ["daytrip", "mamasyada", "to go out / stroll", "", "mah-mas-YAH-dah"],
  ["daytrip", "kumita", "to see / visit", "", "koo-MEE-tah"],
  ["daytrip", "maupod", "to come along", "", "mah-OO-pod"],
  ["daytrip", "huram", "to borrow", "", "HOO-ram"],
  ["daytrip", "Pamasyada kita", "Let's go out", "", "pah-mas-YAH-dah kee-TAH"],
  ["daytrip", "Mamamasyada ako buwas", "I'll go out tomorrow", "", "mah-mah-mas-YAH-dah ah-KAW BOO-was"],
  ["daytrip", "Karuyag ko kumita", "I want to see it", "", "kah-ROO-yag ko koo-MEE-tah"],
  ["daytrip", "Maupod ka buwas?", "Will you come along tomorrow?", "", "mah-OO-pod kah BOO-was"],
  ["daytrip", "Karuyag ko kumita hit San Juanico", "I want to see San Juanico", "", "kah-ROO-yag ko koo-MEE-tah heet san-hwah-NEE-ko"],
  ["daytrip", "Pwede kita magburubaktas", "We can walk around there", "", "PWEH-deh kee-TAH mag-boo-roo-BAK-tas"],
  ["daytrip", "Pagkita kita buwas", "Let's meet tomorrow", "", "pag-KEE-tah kee-TAH BOO-was"],
  ["daytrip", "Mahusay ngadto", "It's beautiful there", "", "mah-hoo-SIGH NGAD-to"],

  // ===== Daily Life — Meals & eating (from PPERFECT_pamasyada_Kita) =====
  ["meals", "pamahaw", "breakfast", "", "pah-MAH-how"],
  ["meals", "paniudto", "lunch", "", "pah-nee-OOD-to"],
  ["meals", "pangiklop", "dinner", "", "pah-NEEK-lop"],
  ["meals", "isnak", "snack", "", "EES-nak"],
  ["meals", "kan-on", "cooked rice", "", "KAN-on"],
  ["meals", "pagkaon", "food", "", "pag-KAH-on"],
  ["meals", "marasa", "delicious", "", "mah-RAH-sah"],
  ["meals", "gutom", "hungry", "", "GOO-tom"],
  ["meals", "Namahaw ka na?", "Have you had breakfast?", "", "nah-MAH-how kah nah"],
  ["meals", "Naniudto ka na?", "Have you had lunch?", "", "nah-nee-OOD-to kah nah"],
  ["meals", "Nangiklop ka na?", "Have you had dinner?", "", "nah-NEEK-lop kah nah"],
  ["meals", "Pamahaw kita", "Let's have breakfast", "", "pah-MAH-how kee-TAH"],
  ["meals", "Ano it paniudtuhon?", "What's for lunch?", "", "AH-no eet pah-nee-ood-TOO-hon"],
  ["meals", "May pagkaon didi", "There's food here", "", "migh pag-KAH-on DEE-dee"],
  ["meals", "Kaon anay", "Eat first", "", "KAH-on AH-nigh"],

  // ===== Daily Life — Cooking (from …Pagluto_hin_Adobo) =====
  ["cook", "lasona", "garlic", "", "lah-SO-nah"],
  ["cook", "sibuyas", "onion", "", "see-BOO-yas"],
  ["cook", "suoy", "vinegar", "", "SOO-oy"],
  ["cook", "toyo", "soy sauce", "", "TOH-yo"],
  ["cook", "tubig", "water", "", "TOO-beeg"],
  ["cook", "pamyenta", "pepper", "", "pam-YEN-tah"],
  ["cook", "asukar", "sugar", "", "ah-SOO-kar"],
  ["cook", "lutuon", "to cook (it)", "from luto", "loo-too-ON"],
  ["cook", "igbabad", "to marinate", "", "eeg-BAH-bad"],
  ["cook", "pakaladkara", "to boil (it)", "", "pah-kah-lad-KAH-rah"],
  ["cook", "panakot", "ingredients / spices", "", "pah-NAH-kot"],
  ["cook", "madali", "easy / quick", "", "mah-dah-LEE"],
  ["cook", "masayon", "easy / simple", "", "mah-SAH-yon"],
  ["cook", "makuri", "hard / difficult", "", "mah-KOO-ree"],
  ["cook", "Ano ini nga kaluto?", "What dish is this?", "", "AH-no ee-NEE ngah kah-LOO-to"],
  ["cook", "Adobo nga manok", "Chicken adobo", "", "ah-DO-bo ngah mah-NOK"],
  ["cook", "Makuri ba ini lutuon?", "Is this hard to cook?", "", "mah-KOO-ree bah ee-NEE loo-too-ON"],
  ["cook", "Madali la", "It's easy", "", "mah-dah-LEE lah"],
  ["cook", "Tutdui gad ako", "Please teach me", "", "toot-DOO-ee gad ah-KAW"],
  ["cook", "Ano it mga panakot?", "What are the ingredients?", "mga = manga (plural)", "AH-no eet mah-NGAH pah-NAH-kot"],

  // ===== Daily Life — When & travel (from PPERFECT_pamasyada_Kita) =====
  ["whentrav", "biyahe", "trip / travel", "", "bee-YAH-heh"],
  ["whentrav", "semana", "week", "", "seh-MAH-nah"],
  ["whentrav", "adlaw", "day", "", "AD-low"],
  ["whentrav", "maabot", "will arrive", "", "mah-AH-bot"],
  ["whentrav", "lumakat", "left / departed", "", "loo-MAH-kat"],
  ["whentrav", "san-o", "when", "", "SAN-o"],
  ["whentrav", "kakan-o", "when (past)", "", "kah-KAN-o"],
  ["whentrav", "Mabiyahe ako ha Pilipinas", "I'll travel to the Philippines", "", "mah-bee-YAH-heh ah-KAW hah pee-lee-PEE-nas"],
  ["whentrav", "Ano ka nga adlaw maabot?", "What day will you arrive?", "", "AH-no kah ngah AD-low mah-AH-bot"],
  ["whentrav", "Kakan-o ka umabot?", "When did you arrive?", "", "kah-KAN-o kah oo-MAH-bot"],
  ["whentrav", "Hit maabot nga duha ka semana", "In the coming two weeks", "duha = two", "heet mah-AH-bot ngah DOO-hah kah seh-MAH-nah"],

  // ===== Basics grammar — Describing sentences (from …Adobo doc) =====
  ["gram", "bata", "child", "", "BAH-tah"],
  ["gram", "uyab", "girlfriend / boyfriend", "", "OO-yab"],
  ["gram", "mabaho", "smelly", "", "mah-BAH-ho"],
  ["gram", "an", "the (completed / past)", "marks the subject", "ahn"],
  ["gram", "it", "the (now / general)", "marks the subject", "eet"],
  ["gram", "Gwapo it bata", "The child is handsome", "it = the (now)", "GWAH-po eet BAH-tah"],
  ["gram", "Gwapo an bata", "The child was handsome", "an = the (past)", "GWAH-po ahn BAH-tah"],
  ["gram", "Hataas it akon uyab", "My girlfriend is tall", "", "hah-TAH-as eet AH-kon OO-yab"],
  ["gram", "Marasa it adobo", "The adobo is tasty", "", "mah-RAH-sah eet ah-DO-bo"],
  ["gram", "Mabaho it jeep", "The jeepney is smelly", "", "mah-BAH-ho eet jeep"],

  // ===== Basics grammar — Verbs in action (Mag/Nag, from …Adobo doc) =====
  ["gram", "Magluluto it bata", "The child will cook", "future", "mag-loo-LOO-to eet BAH-tah"],
  ["gram", "Nagluluto it bata", "The child is cooking", "present", "nag-loo-LOO-to eet BAH-tah"],
  ["gram", "Nagluto an bata", "The child cooked", "past", "nag-LOO-to ahn BAH-tah"],

  // ===== Numbers, Days & Colors (from Wikivoyage Waray phrasebook) =====
  ["num", "usa", "one", "", "oo-SAH"],
  ["num", "duha", "two", "", "doo-HAH"],
  ["num", "tulo", "three", "", "too-LO"],
  ["num", "upat", "four", "", "oo-PAT"],
  ["num", "lima", "five", "", "lee-MAH"],
  ["num", "unom", "six", "", "oo-NOM"],
  ["num", "pito", "seven", "", "pee-TO"],
  ["num", "walo", "eight", "", "wah-LO"],
  ["num", "siyam", "nine", "", "see-YAM"],
  ["num", "napulo", "ten", "", "nah-poo-LO"],
  ["num", "karuhaan", "twenty", "", "kah-roo-HAH-an"],
  ["num", "usa kagatos", "one hundred", "", "oo-SAH kah-GAH-tos"],

  ["cal", "Lunes", "Monday", "", "LOO-nes"],
  ["cal", "Martes", "Tuesday", "", "MAR-tes"],
  ["cal", "Miyerkoles", "Wednesday", "", "mee-YER-ko-les"],
  ["cal", "Huwebes", "Thursday", "", "hoo-WEH-bes"],
  ["cal", "Biyernes", "Friday", "", "bee-YER-nes"],
  ["cal", "Sabado", "Saturday", "", "SAH-bah-do"],
  ["cal", "Dominggo", "Sunday", "", "do-MEENG-go"],
  ["cal", "Enero", "January", "", "eh-NEH-ro"],
  ["cal", "Pebrero", "February", "", "peb-REH-ro"],
  ["cal", "Marso", "March", "", "MAR-so"],
  ["cal", "Abril", "April", "", "ahb-REEL"],
  ["cal", "Mayo", "May", "", "MAH-yo"],
  ["cal", "Hunyo", "June", "", "HOON-yo"],
  ["cal", "Hulyo", "July", "", "HOOL-yo"],
  ["cal", "Agosto", "August", "", "ah-GOS-to"],
  ["cal", "Setyembre", "September", "", "set-YEM-breh"],
  ["cal", "Oktubre", "October", "", "ok-TOO-breh"],
  ["cal", "Nobyembre", "November", "", "nob-YEM-breh"],
  ["cal", "Disyembre", "December", "", "dis-YEM-breh"],

  ["color", "itom", "black", "", "EE-tom"],
  ["color", "busag", "white", "", "BOO-sag"],
  ["color", "pula", "red", "", "POO-lah"],
  ["color", "asul", "blue", "", "ah-SOOL"],
  ["color", "darag", "yellow", "", "DAH-rag"],
  ["color", "berde", "green", "", "BER-deh"],

  ["essent", "Waray ako makabaro", "I don't understand", "", "wah-RIGH ah-KAW mah-kah-BAH-ro"],
  ["essent", "Hain an CR?", "Where is the CR? (bathroom)", "an = the; ang is Tagalog", "HAH-een ahn see-AR"],
  ["essent", "Buligi daw ako", "Please help me", "", "boo-LEE-gee dow ah-KAW"],
  ["essent", "Pasaylo-a ako", "Excuse me / sorry", "", "pah-sigh-LO-ah ah-KAW"],
  ["essent", "Sige, sunod na la", "Goodbye (see you next time)", "", "SEE-geh SOO-nod nah lah"],

  // ===== Building Blocks — possessives II-class (Peace Corps L4) =====
  ["poss", "nakon", "my", "short form: ko", "NAH-kon"],
  ["poss", "ko", "my (short)", "", "ko"],
  ["poss", "nimo", "your", "short form: mo", "NEE-mo"],
  ["poss", "niya", "his / her", "", "nee-YAH"],
  ["poss", "naton", "our (incl)", "", "NAH-ton"],
  ["poss", "namon", "our (excl)", "", "NAH-mon"],
  ["poss", "niyo", "your (pl)", "", "NEE-yo"],
  ["poss", "nira", "their", "", "NEE-rah"],
  ["poss", "libro nakon", "my book", "", "LEE-bro NAH-kon"],
  ["poss", "lapis nimo", "your pencil", "", "LAH-pees NEE-mo"],
  ["poss", "uyab niya", "his / her sweetheart", "", "OO-yab nee-YAH"],
  ["poss", "balay namon", "our house", "", "bah-LIGH NAH-mon"],
  // ===== Building Blocks — possessives III-class (Peace Corps L8) =====
  ["poss", "akon", "mine / my", "", "AH-kon"],
  ["poss", "imo", "yours / your", "", "EE-mo"],
  ["poss", "iya", "his / hers", "", "ee-YAH"],
  ["poss", "aton", "ours (incl)", "", "AH-ton"],
  ["poss", "amon", "ours (excl)", "", "AH-mon"],
  ["poss", "iyo", "yours (pl)", "", "EE-yo"],
  ["poss", "ira", "theirs", "", "EE-rah"],
  ["poss", "Akon ini", "This is mine", "", "AH-kon ee-NEE"],
  ["poss", "Akon ini nga balay", "This house is mine", "", "AH-kon ee-NEE ngah bah-LIGH"],
  ["poss", "ha akon", "to / for me", "", "hah AH-kon"],
  ["poss", "ha imo", "to / for you", "", "hah EE-mo"],
  ["poss", "ha iya", "to / for him / her", "", "hah ee-YAH"],

  // ===== Building Blocks — demonstratives (Peace Corps L3) =====
  ["demo", "ini", "this (near)", "", "ee-NEE"],
  ["demo", "iton", "that (near you)", "", "ee-TON"],
  ["demo", "adto", "that (over there)", "", "AD-to"],
  ["demo", "kahoy", "tree", "", "KAH-hoy"],
  ["demo", "libro", "book", "", "LEE-bro"],
  ["demo", "ini nga babaye", "this woman", "", "ee-NEE ngah bah-BAH-yeh"],
  ["demo", "iton nga lalake", "that man", "", "ee-TON ngah lah-LAH-keh"],
  ["demo", "adto nga bata", "that child over there", "", "AD-to ngah BAH-tah"],
  ["demo", "Tubig ini", "This is water", "", "TOO-beeg ee-NEE"],
  ["demo", "Kahoy adto", "That's a tree over there", "", "KAH-hoy AD-to"],
  ["demo", "Mga libro ini", "These are books", "", "mah-NGAH LEE-bro ee-NEE"],

  // ===== Building Blocks — markers (Peace Corps L2 / L6) =====
  ["mark", "hi", "the (before a name)", "name marker", "hee"],
  ["mark", "hin", "a / some (object)", "object marker", "heen"],
  ["mark", "han", "of / the (past object)", "", "hahn"],
  ["mark", "ha", "to / at / in", "", "hah"],
  ["mark", "ngan", "and", "", "ngahn"],
  ["mark", "saging", "banana", "", "SAH-geeng"],
  ["mark", "Ako hi Peter", "I am Peter", "", "ah-KAW hee PEE-ter"],
  ["mark", "Hira Perla ngan Tessie", "They are Perla and Tessie", "", "HEE-rah PER-lah ngahn TES-see"],
  ["mark", "Mapalit ako hin saging", "I'll buy a banana", "", "mah-PAH-leet ah-KAW heen SAH-geeng"],
  ["mark", "Makadto ako ha balay", "I'll go to the house", "", "mah-KAD-to ah-KAW hah bah-LIGH"],

  // ===== Building Blocks — question words (Peace Corps L10-12 / L28) =====
  ["qword", "hin-o", "who", "", "heen-O"],
  ["qword", "ano", "what", "", "AH-no"],
  ["qword", "hain", "where", "", "HAH-een"],
  ["qword", "diin", "where (from / which)", "", "dee-EEN"],
  ["qword", "kay ano", "why", "", "kigh AH-no"],
  ["qword", "mapira", "how many", "", "mah-PEE-rah"],
  ["qword", "tagpira", "how much", "", "tag-PEE-rah"],
  ["qword", "ba", "makes a yes/no question", "particle", "bah"],
  ["qword", "Hin-o hiya?", "Who is she?", "", "heen-O hee-YAH"],
  ["qword", "Isda ba ini?", "Is this fish?", "", "ees-DAH bah ee-NEE"],
  ["qword", "Kay ano?", "Why?", "", "kigh AH-no"],
  ["qword", "Mapira?", "How many?", "", "mah-PEE-rah"],

  // ===== Building Blocks — particles & negation (Peace Corps L16 / L20) =====
  ["ptcl", "na", "already", "", "nah"],
  ["ptcl", "pa", "still / yet", "", "pah"],
  ["ptcl", "liwat", "also / too", "", "LEE-wat"],
  ["ptcl", "hin duro", "very / a lot", "", "heen DOO-ro"],
  ["ptcl", "Marasa hin duro", "Very delicious", "", "mah-RAH-sah heen DOO-ro"],
  ["ptcl", "Namahaw na ako", "I've already had breakfast", "", "nah-MAH-how nah ah-KAW"],
  ["ptcl", "Diri pa", "Not yet / still not", "", "DEE-ree pah"],
  ["ptcl", "Makusog liwat", "Strong too", "", "mah-KOO-sog LEE-wat"],

  // ===== Building Blocks — ma- verb tenses (Peace Corps L5 conjugation) =====
  ["gram", "makaon", "will eat", "future: ma-", "mah-KAH-on"],
  ["gram", "nakaon", "is eating", "present: na-", "nah-KAH-on"],
  ["gram", "kinmaon", "ate", "past: -inm-", "kin-MAH-on"],
  ["gram", "malakat", "will go", "future: ma-", "mah-LAH-kat"],
  ["gram", "nalakat", "is going", "present: na-", "nah-LAH-kat"],
  ["gram", "linmakat", "went", "past: -inm-", "lin-MAH-kat"],
  ["gram", "mapalit", "will buy", "future: ma-", "mah-PAH-leet"],
  ["gram", "napalit", "is buying", "present: na-", "nah-PAH-leet"],
  ["gram", "pinmalit", "bought", "past: -inm-", "pin-MAH-leet"],
  ["gram", "mainom", "will drink", "future: ma-", "mah-EE-nom"],
  ["gram", "nainom", "is drinking", "present: na-", "nah-EE-nom"],
  ["gram", "inminom", "drank", "past: -inm-", "een-MEE-nom"],

  // ===== Building Blocks — modals (Peace Corps L22) =====
  ["modal", "kinahanglan", "need to / must", "", "kee-nah-HANG-lan"],
  ["modal", "mahimo", "can / able to", "same as pwede", "mah-HEE-mo"],
  ["modal", "Ayaw", "don't (command)", "", "AH-yaw"],
  ["modal", "trabaho", "work", "magtrabaho = to work", "trah-BAH-ho"],
  ["modal", "Kinahanglan ako magtrabaho", "I need to work", "", "kee-nah-HANG-lan ah-KAW mag-trah-BAH-ho"],
  ["modal", "Pwede ka ba magdara?", "Can you bring it?", "", "PWEH-deh kah bah mag-DAH-rah"],
  ["modal", "Mahimo ako maupod", "I can come along", "", "mah-HEE-mo ah-KAW mah-OO-pod"],
  ["modal", "Ayaw pagkaon", "Don't eat", "", "AH-yaw pag-KAH-on"],

  // ===== Full curriculum: new vocab (course + Tramp/Zorc dictionary verified) =====
  // -- people & family --
  ["ppl", "anak", "child", "", "ah-NAK"],
  ["ppl", "apoy", "grandparent", "", "ah-POY"],
  ["ppl", "apo", "grandchild", "", "ah-PO"],
  ["ppl", "bugto", "sibling", "", "BOOG-to"],
  ["ppl", "tawo", "person", "", "TAH-wo"],
  ["ppl", "miyembro", "member", "", "mee-YEM-bro"],
  ["ppl", "ulitawo", "young man", "", "oo-lee-TAH-wo"],
  ["ppl", "daragita", "young woman", "", "dah-rah-GEE-tah"],
  ["ppl", "lagas", "old person", "", "LAH-gas"],
  ["ppl", "kaharani", "neighbor", "", "kah-hah-RAH-nee"],
  // -- jobs & roles --
  ["ppl", "nars", "nurse", "", "nars"],
  ["ppl", "panday", "carpenter", "", "PAN-digh"],
  ["ppl", "pastor", "pastor", "", "PAS-tor"],
  ["ppl", "misyonaryo", "missionary", "", "mees-yo-NAR-yo"],
  ["ppl", "abugado", "lawyer", "", "ah-boo-GAH-do"],
  ["ppl", "mangingisda", "fisherman", "", "mah-ngee-NGEES-dah"],
  ["ppl", "mag-uroma", "farmer", "", "mag-oo-ROH-mah"],
  ["ppl", "direktor", "director", "", "dee-rek-TOR"],
  ["ppl", "kapitan", "captain", "", "kah-pee-TAN"],
  ["ppl", "mayor", "mayor / boss", "", "MAH-yor"],
  ["ppl", "konsehal", "councilman", "", "kon-SEH-hal"],
  ["ppl", "negosyante", "businessman", "", "neh-gos-YAN-teh"],
  ["ppl", "sekretarya", "secretary", "", "sek-reh-TAR-yah"],
  ["ppl", "hardinero", "gardener", "", "har-dee-NEH-ro"],
  ["ppl", "tag-iya", "owner", "", "tag-ee-YAH"],
  ["ppl", "ninong", "godfather", "", "NEE-nong"],
  ["ppl", "pasyente", "patient", "", "pas-YEN-teh"],
  // -- the body --
  ["ppl", "lawas", "body", "", "LAH-was"],
  ["ppl", "nawong", "face", "", "nah-WONG"],
  ["ppl", "mata", "eye", "", "mah-TAH"],
  ["ppl", "ulo", "head", "", "OO-lo"],
  ["ppl", "kasingkasing", "heart", "", "kah-seeng-KAH-seeng"],
  // -- describing (adjectives) --
  ["week1", "daku", "big", "", "dah-KOO"],
  ["week1", "gutiay", "small", "", "goo-TEE-igh"],
  ["week1", "habubo", "short", "", "hah-boo-BO"],
  ["week1", "magasa", "thin", "", "mah-GAH-sah"],
  ["week1", "hubya", "lazy", "", "HOOB-yah"],
  ["week1", "kapoy", "tired", "", "kah-POY"],
  ["week1", "maraut", "bad", "", "mah-RAH-oot"],
  ["week1", "grabe", "serious", "", "GRAH-beh"],
  ["week1", "matidong", "righteous", "", "mah-tee-DONG"],
  ["week1", "maalsom", "sour", "", "mah-AL-som"],
  ["week1", "matam-is", "sweet", "", "mah-TAM-ees"],
  ["week1", "matab-ang", "tasteless", "", "mah-tab-ANG"],
  ["week1", "daan", "old (things)", "", "dah-AN"],
  ["week1", "bag-o", "new", "", "BAG-o"],
  // -- verbs --
  ["verbs", "hatag", "to give", "", "HAH-tag"],
  ["verbs", "bayad", "to pay", "", "BAH-yad"],
  ["verbs", "hulam", "to borrow", "", "HOO-lam"],
  ["verbs", "lingkod", "to sit", "", "leeng-KOD"],
  ["verbs", "tindog", "to stand", "", "TEEN-dog"],
  ["verbs", "sulod", "to enter", "", "soo-LOD"],
  ["verbs", "buhat", "to do / make", "", "BOO-hat"],
  ["verbs", "saka", "to climb", "", "SAH-kah"],
  ["verbs", "lakso", "to jump", "", "LAK-so"],
  ["verbs", "dalagan", "to run", "", "dah-LAH-gan"],
  ["verbs", "uli", "to go home", "", "oo-LEE"],
  ["verbs", "abot", "to arrive", "", "ah-BOT"],
  ["verbs", "pili", "to choose", "", "PEE-lee"],
  ["verbs", "surat", "to write", "", "SOO-rat"],
  ["verbs", "siring", "to speak / say", "", "SEE-ring"],
  ["verbs", "ampo", "to pray", "", "AM-po"],
  ["verbs", "simba", "to worship", "", "SEEM-bah"],
  ["verbs", "tanum", "to plant", "", "TAH-noom"],
  ["verbs", "luhod", "to kneel", "", "loo-HOD"],
  ["verbs", "hangyo", "to ask a favor", "", "hang-YO"],
  ["verbs", "tukar", "to play music", "", "TOO-kar"],
  ["verbs", "kanta", "to sing", "", "KAN-tah"],
  ["verbs", "dara", "to bring", "", "DAH-rah"],
  ["verbs", "labay", "to pass by", "", "lah-BIGH"],
  // -- home & things --
  ["verbs", "lamesa", "table", "", "lah-MEH-sah"],
  ["verbs", "lingkuran", "chair", "", "leeng-KOO-ran"],
  ["verbs", "katre", "bed", "", "KAT-reh"],
  ["verbs", "kudal", "fence", "", "koo-DAL"],
  ["verbs", "sala", "living room", "also: sin", "SAH-lah"],
  ["verbs", "tsinelas", "slippers", "", "tsee-NEH-las"],
  ["verbs", "saruwal", "pants", "", "sah-roo-WAL"],
  ["verbs", "syaket", "jacket", "", "SYAH-ket"],
  ["verbs", "medyas", "socks", "", "MED-yas"],
  ["verbs", "papel", "paper", "", "pah-PEL"],
  ["verbs", "lapis", "pencil", "", "LAH-pees"],
  ["verbs", "mulayan", "toy", "", "moo-LAH-yan"],
  ["verbs", "telebisyon", "television", "", "teh-leh-BEES-yon"],
  ["verbs", "sista", "guitar", "", "SEES-tah"],
  ["verbs", "mensahe", "message", "", "men-SAH-heh"],
  ["verbs", "tambal", "medicine", "", "TAM-bal"],
  // -- food --
  ["meals", "mangga", "mango", "", "MANG-gah"],
  ["meals", "nangka", "jackfruit", "", "NANG-kah"],
  ["meals", "kamatis", "tomato", "", "kah-MAH-tees"],
  ["meals", "mais", "corn", "", "mah-EES"],
  ["meals", "tsa", "tea", "", "tsah"],
  ["meals", "sabaw", "soup", "", "SAH-bow"],
  ["meals", "keyk", "cake", "", "keyk"],
  ["meals", "prutas", "fruit", "", "PROO-tas"],
  // -- nature & animals --
  ["nature", "dagat", "sea", "", "dah-GAT"],
  ["nature", "bukad", "flower", "", "boo-KAD"],
  ["nature", "tuna", "land / earth", "", "TOO-nah"],
  ["nature", "langit", "sky / heaven", "", "LAH-ngeet"],
  ["nature", "ayam", "dog", "also: ido", "AH-yam"],
  ["nature", "karabaw", "carabao", "", "kah-rah-BOW"],
  // -- time --
  ["verbs", "panahon", "time / weather", "", "pah-nah-HON"],
  ["verbs", "didto", "there (far)", "", "DEED-to"],
  ["greet", "Maupay nga udto", "Good noon", "", "mah-OO-pigh ngah OOD-to"],
  // -- faith & church --
  ["faith", "Diyos", "God", "", "dee-YOS"],
  ["faith", "Ginoo", "Lord", "", "gee-NO-o"],
  ["faith", "Jesu Kristo", "Jesus Christ", "", "HEH-soo KREES-to"],
  ["faith", "espiritu", "spirit", "", "es-pee-ree-TOO"],
  ["faith", "gugma", "love", "", "GOOG-mah"],
  ["faith", "bendisyon", "blessing", "", "ben-DEES-yon"],
  ["faith", "simbahan", "church", "from 'simba' — to worship", "seem-BAH-han"],
  ["faith", "Kristohanon", "Christian", "", "krees-to-HAH-non"],
  ["faith", "Bibliya", "Bible", "", "beeb-LEE-yah"],
  ["faith", "kros", "cross", "", "kros"],
  ["faith", "kinabuhi", "life", "", "kee-nah-BOO-hee"],
  ["faith", "kaadlawan", "birthday", "", "kah-ad-LAH-wan"],
  ["faith", "pasaylo", "to forgive", "", "pah-SIGH-lo"],
  ["faith", "wali", "to preach", "", "WAH-lee"],
  ["faith", "sala nga buhat", "sin", "lit. wrong deed", "SAH-lah ngah BOO-hat"],

  // ===== simple survival words (swapped into Survival Kit) =====
  ["greet", "maupay", "good", "", "mah-OO-pigh"],
  ["greet", "tabang", "help", "as in “Tabang!”", "tah-BANG"],
  ["greet", "Gusto ko", "I like", "", "GOOS-to ko"],
];

// Cards Paul's old tracker logged as "Forgotten" — start these a notch lower.
export const FORGOTTEN = new Set([
  "buoton", "riko", "kita", "makusog", "asawa", "Naintindihan nimo?",
  "Mahusay ka", "sangkay", "ako", "nanay", "matambok", "hataas",
  "babaye", "lalaki", "hira", "mapaso", "Nakikit-an mo?", "Maraksot ka",
  "Ano imo gin-kakaon?", "kamo", "bisita", "Oo, nakikit-an ko",
]);
