/* Waray (Challenger · Daram) — GENERATED by tools/build-challenger.mjs (do not hand-edit
   lightly). Phase 1 (revised, Gemini API; decks ch1–ch7, A0) + Phase 2 (decks ch8–ch12, A1).
   Card shape: [deck, waray, english, subtext, respelling, example?]. example = {war,focus,en}
   for single-word cards (the in-context flashcard hint); null for phrases.
   Curriculum references cards by Waray. MARKERS stay out of the deck (taught in apply phrases
   + stories). Dialect-uncertain forms carry a note + go to the Ask Ella queue. */

export const SEED_CH = [
  ["ch1","maupay","good","","",{"war":"Maupay nga aga.","focus":"Maupay","en":"Good morning."}],
  ["ch1","aga","morning","","",{"war":"Maupay nga aga.","focus":"aga","en":"Good morning."}],
  ["ch1","kulop","afternoon","","",{"war":"Maupay nga kulop.","focus":"kulop","en":"Good afternoon."}],
  ["ch1","gab-i","evening/night","","",{"war":"Maupay nga gab-i.","focus":"gab-i","en":"Good evening."}],
  ["ch1","ako","I/me","Independent pronoun, usually topic.","",{"war":"Ako hi Juan.","focus":"Ako","en":"I am Juan."}],
  ["ch1","ikaw","you (sg)","Independent pronoun, usually topic.","",{"war":"Ikaw hi Maria?","focus":"Ikaw","en":"Are you Maria?"}],
  ["ch1","kamusta","hello/how are you","","",{"war":"Kamusta ikaw?","focus":"Kamusta","en":"How are you?"}],
  ["ch1","salamat","thanks","","",{"war":"Salamat, Nanay.","focus":"Salamat","en":"Thanks, Mom."}],
  ["ch1","sige","ok/go ahead","","",{"war":"Sige, maupay nga gab-i.","focus":"Sige","en":"Okay, good night."}],
  ["ch1","Maupay nga aga!","Good morning!","","",null],
  ["ch1","Maupay nga gab-i.","Good evening.","","",null],
  ["ch1","Kamusta ikaw?","How are you?","","",null],
  ["ch1","Ako hi Ana.","I am Ana.","","",null],
  ["ch1","Salamat.","Thanks.","","",null],
  ["ch1","Sige.","Okay.","","",null],
  ["ch2","diri","no/not","","",{"war":"Diri, diri ako.","focus":"Diri","en":"No, not me."}],
  ["ch2","hain","where","","",{"war":"Hain an balay?","focus":"Hain","en":"Where is the house?"}],
  ["ch2","hiya","he/she/it","Independent pronoun, usually topic. Gender-neutral.","",{"war":"Hiya an nanay.","focus":"Hiya","en":"He/she is the mother."}],
  ["ch2","aadi","here (near speaker)","","",{"war":"Aadi ako.","focus":"Aadi","en":"I am here."}],
  ["ch2","aada","there (near listener)","","",{"war":"Aada hiya.","focus":"Aada","en":"He/she is there (near you)."}],
  ["ch2","didto","over there (far from both)","","",{"war":"Didto an balay.","focus":"Didto","en":"The house is over there."}],
  ["ch2","dadi","come here","Often used as an imperative.","",{"war":"Dadi!","focus":"Dadi","en":"Come here!"}],
  ["ch2","asawa","spouse","Gender-neutral.","",{"war":"An akon asawa.","focus":"asawa","en":"My spouse."}],
  ["ch2","anak","child","","",{"war":"An akon anak.","focus":"anak","en":"My child."}],
  ["ch2","nanay","mother","","",{"war":"An akon nanay.","focus":"nanay","en":"My mother."}],
  ["ch2","tatay","father","","",{"war":"An akon tatay.","focus":"tatay","en":"My father."}],
  ["ch2","balay","house","","",{"war":"An balay ni Ana.","focus":"balay","en":"Ana's house."}],
  ["ch2","Balite","Balite (village in Daram)","A specific location in Daram, Samar.","",{"war":"Didto ha Balite.","focus":"Balite","en":"Over there in Balite."}],
  ["ch2","Hain hi Nanay?","Where is Mom?","","",null],
  ["ch2","Aadi hiya.","She is here.","","",null],
  ["ch2","Diri hiya aadi.","He/she is not here.","","",null],
  ["ch2","Aada an balay.","The house is there (near you).","","",null],
  ["ch2","Didto ha Balite.","Over there in Balite.","","",null],
  ["ch2","Dadi, anak ko!","Come here, my child!","","",null],
  ["ch3","gusto","want/like","","",{"war":"Gusto ko kape.","focus":"Gusto","en":"I want coffee."}],
  ["ch3","tubig","water","","",{"war":"Gusto ko tubig.","focus":"tubig","en":"I want water."}],
  ["ch3","kape","coffee","","",{"war":"Gusto mo kape?","focus":"kape","en":"Do you want coffee?"}],
  ["ch3","alayon","please","","",{"war":"Alayon, tubig.","focus":"Alayon","en":"Please, water."}],
  ["ch3","kaon","eat","","",{"war":"Kaon na!","focus":"Kaon","en":"Eat now!"}],
  ["ch3","inom","drink","","",{"war":"Inom kape.","focus":"Inom","en":"Drink coffee."}],
  ["ch3","kan-on","cooked rice","","",{"war":"Gusto ko kan-on.","focus":"kan-on","en":"I want cooked rice."}],
  ["ch3","oo","yes","","",{"war":"Oo, gusto ko.","focus":"Oo","en":"Yes, I want."}],
  ["ch3","Gusto ko tubig.","I want water.","","",null],
  ["ch3","Gusto mo kape?","Do you want coffee?","","",null],
  ["ch3","Oo, gusto ko kape.","Yes, I want coffee.","","",null],
  ["ch3","Alayon, kan-on.","Please, cooked rice.","","",null],
  ["ch3","Kaon na.","Eat now.","","",null],
  ["ch3","Inom tubig.","Drink water.","","",null],
  ["ch4","akon","my/mine","Pre-posed possessive/agent pronoun for 'I'.","",{"war":"Akon nga balay.","focus":"Akon","en":"My house."}],
  ["ch4","imo","your/yours (sg)","Pre-posed possessive/agent pronoun for 'you (sg)'.","",{"war":"Imo anak.","focus":"Imo","en":"Your child."}],
  ["ch4","iya","his/her/hers","Pre-posed possessive/agent pronoun for 'he/she/it'.","",{"war":"Iya balay.","focus":"Iya","en":"His/her house."}],
  ["ch4","ko","my/I (agent, enclitic)","Enclitic possessive/agent pronoun for 'I'.","",{"war":"Kape ko.","focus":"ko","en":"My coffee."}],
  ["ch4","mo","your/you (agent, enclitic)","Enclitic possessive/agent pronoun for 'you (sg)'.","",{"war":"Tubig mo.","focus":"mo","en":"Your water."}],
  ["ch4","na","his/her/he-she (agent, enclitic)","Enclitic possessive/agent pronoun for 'he/she/it'. 3rd-person agent — standard Waray is 'niya'; confirm Daram uses 'na'.","",{"war":"Balay na.","focus":"na","en":"His/her house."}],
  ["ch4","Akon balay ini.","This is my house.","","",null],
  ["ch4","Imo ba ini nga kape?","Is this your coffee?","","",null],
  ["ch4","Oo, kape ko ini.","Yes, this is my coffee.","","",null],
  ["ch4","An anak na aada.","His/her child is there.","","",null],
  ["ch4","Gusto ko an imo tubig.","I want your water.","","",null],
  ["ch4","Gusto niya kan-on.","He/she wants cooked rice.","","",null],
  ["ch5","usa","one","","",{"war":"Usa nga balay.","focus":"Usa","en":"One house."}],
  ["ch5","duha","two","","",{"war":"Duha nga anak.","focus":"Duha","en":"Two children."}],
  ["ch5","tulo","three","","",{"war":"Tulo nga kape.","focus":"Tulo","en":"Three coffees."}],
  ["ch5","upat","four","","",{"war":"Upat nga pesos.","focus":"Upat","en":"Four pesos."}],
  ["ch5","lima","five","","",{"war":"Lima nga tubig.","focus":"Lima","en":"Five waters."}],
  ["ch5","pira","how many/how much (quantity)","","",{"war":"Pira an tubig?","focus":"Pira","en":"How much water?"}],
  ["ch5","tagpira","how much each","","",{"war":"Tagpira an kape?","focus":"Tagpira","en":"How much is the coffee (each)?"}],
  ["ch5","palit","buy","Root form, often used as imperative.","",{"war":"Palit kape.","focus":"Palit","en":"Buy coffee."}],
  ["ch5","mapalit","will buy","Future tense of 'palit'.","",{"war":"Mapalit ako tubig.","focus":"Mapalit","en":"I will buy water."}],
  ["ch5","pesos","pesos (currency)","","",{"war":"Lima ka pesos.","focus":"pesos","en":"Five pesos."}],
  ["ch5","Pira nga tubig?","How many waters?","","",null],
  ["ch5","Usa nga tubig.","One water.","","",null],
  ["ch5","Tagpira an kape?","How much is the coffee (each)?","","",null],
  ["ch5","Lima ka pesos.","Five pesos.","","",null],
  ["ch5","Mapalit ako duha nga kape.","I will buy two coffees.","","",null],
  ["ch5","Salamat, Tatay.","Thanks, Dad.","","",null],
  ["ch6","udto","noon","","",{"war":"Ha udto.","focus":"udto","en":"At noon."}],
  ["ch6","yana","now","","",{"war":"Kaon yana.","focus":"yana","en":"Eat now."}],
  ["ch6","adlaw","day/sun","","",{"war":"Yana nga adlaw.","focus":"adlaw","en":"Today (this day)."}],
  ["ch6","kahapon","yesterday","","",{"war":"Kaon kahapon.","focus":"kahapon","en":"Ate yesterday."}],
  ["ch6","buwas","tomorrow","","",{"war":"Inom buwas.","focus":"buwas","en":"Drink tomorrow."}],
  ["ch6","san-o","when (question)","","",{"war":"San-o ka kaon?","focus":"San-o","en":"When will you eat?"}],
  ["ch6","Kaon yana.","Eat now.","","",null],
  ["ch6","Mapalit ako buwas.","I will buy tomorrow.","","",null],
  ["ch6","San-o ka inom kape?","When will you drink coffee?","","",null],
  ["ch6","Nag-inom ako kahapon.","I drank yesterday.","","",null],
  ["ch6","Ha udto an kaon.","The eating is at noon.","","",null],
  ["ch6","Yana nga gab-i.","Tonight.","","",null],
  ["ch7","kita","we (inclusive, you and I)","Independent pronoun, includes listener.","",{"war":"Kaon kita.","focus":"kita","en":"Let's eat (you and I)."}],
  ["ch7","kami","we (exclusive, I and others, not you)","Independent pronoun, excludes listener.","",{"war":"Kami an asawa.","focus":"Kami","en":"We (not you) are the spouses."}],
  ["ch7","kamo","you (plural)","Independent pronoun.","",{"war":"Kamusta kamo?","focus":"kamo","en":"How are you all?"}],
  ["ch7","hira","they/them","Independent pronoun.","",{"war":"Hira an anak.","focus":"Hira","en":"They are the children."}],
  ["ch7","aton","our/ours (inclusive)","Pre-posed possessive/agent pronoun, includes listener.","",{"war":"Aton balay.","focus":"Aton","en":"Our (inclusive) house."}],
  ["ch7","amon","our/ours (exclusive)","Pre-posed possessive/agent pronoun, excludes listener.","",{"war":"Amon kape.","focus":"Amon","en":"Our (exclusive) coffee."}],
  ["ch7","iyo","your/yours (plural)","Pre-posed possessive/agent pronoun.","",{"war":"Iyo tubig.","focus":"Iyo","en":"Your (plural) water."}],
  ["ch7","ira","their/theirs","Pre-posed possessive/agent pronoun.","",{"war":"Ira kan-on.","focus":"Ira","en":"Their cooked rice."}],
  ["ch7","ta","our/we (agent, inclusive, enclitic)","Enclitic possessive/agent pronoun, includes listener. inclusive agent enclitic — confirm Daram form.","",{"war":"Balay ta.","focus":"ta","en":"Our (inclusive) house."}],
  ["ch7","mi","our/we (agent, exclusive, enclitic)","Enclitic possessive/agent pronoun, excludes listener. exclusive agent enclitic — standard is 'namon'; confirm 'mi'.","",{"war":"Gusto mi.","focus":"mi","en":"We (exclusive) want."}],
  ["ch7","niyo","your/you (agent, plural, enclitic)","Enclitic possessive/agent pronoun. 'niyo' is common after nouns. plural agent — confirm Daram form.","",{"war":"Kape niyo.","focus":"niyo","en":"Your (plural) coffee."}],
  ["ch7","nira","their/they (agent, enclitic)","Enclitic possessive/agent pronoun. 'nira' is common after nouns. their/agent — confirm Daram form.","",{"war":"Kan-on nira.","focus":"nira","en":"Their cooked rice."}],
  ["ch7","Kaon kita yana.","Let's eat now (you and I).","","",null],
  ["ch7","Kami mapalit tubig.","We (not you) will buy water.","","",null],
  ["ch7","Kamusta kamo?","How are you all?","","",null],
  ["ch7","Iyo balay ini.","This is your (plural) house.","","",null],
  ["ch7","Gusto nira kape.","They want coffee.","","",null],
  ["ch7","Amon mga anak.","Our (exclusive) children.","","",null],
  ["ch8","apo","grandparent / elder","also any respected elder",""],
  ["ch8","mano","older brother","respectful title for any older man",""],
  ["ch8","mana","older sister","respectful title for any older woman",""],
  ["ch8","bana","husband","vs asawa = spouse",""],
  ["ch8","nalipay","glad / happy","'glad to meet you'; inflected — confirm w/ Ella",""],
  ["ch8","kila","meet","as in makakila; confirm w/ Ella",""],
  ["ch9","lingkuran","chair","seat or bench",""],
  ["ch9","lamesa","table","Spanish loan",""],
  ["ch9","banga","clay jar","stores cool drinking water",""],
  ["ch9","kutsara","spoon","",""],
  ["ch9","tinidor","fork","",""],
  ["ch9","kadi","come here / bring","'pass me / bring that'",""],
  ["ch9","brayong","broom","coconut-midrib yard broom; confirm w/ Ella",""],
  ["ch10","kain","where (going)","Kain ka? = where are you going?",""],
  ["ch10","madto","will go","go to a far place",""],
  ["ch10","pakadto","heading to","going toward",""],
  ["ch10","tindahan","store","the sari-sari store",""],
  ["ch10","pantalan","pier","",""],
  ["ch10","uma","farm","fields or plantation",""],
  ["ch11","mapaso","hot","weather or food",""],
  ["ch11","uran","rain","",""],
  ["ch11","umuuran","raining","'it's raining now'; inflected — confirm w/ Ella",""],
  ["ch11","hangin","wind","also air",""],
  ["ch11","mahagkot","cold","chilly breeze, cold drink",""],
  ["ch11","kamapas","humid","sticky coastal heat; confirm w/ Ella",""],
  ["ch11","masyado","very","amplifier; Tagalog loan — confirm w/ Ella",""],
  ["ch12","nganay","first","'for a moment / first'",""],
  ["ch12","buhat","do / make","tasks, chores",""],
  ["ch12","trabaho","work / job","Spanish loan",""],
  ["ch12","pahuway","rest","",""],
];

export const FORGOTTEN_CH = new Set();

export const CHALLENGER = [
  {
    "id": "cp1",
    "name": "First Steps in Daram",
    "hint": "Greetings, people, home, food, buying, time, and pronouns",
    "units": [
      {
        "id": "cu1",
        "name": "Maupay nga Aga!",
        "hint": "Greetings & Introductions",
        "lessons": [
          {
            "id": "cu1l1",
            "title": "Greetings",
            "items": [
              "maupay",
              "aga",
              "kulop",
              "gab-i"
            ]
          },
          {
            "id": "cu1l2",
            "title": "Me and You",
            "items": [
              "ako",
              "ikaw",
              "kamusta"
            ]
          },
          {
            "id": "cu1l3",
            "title": "Saying Thanks",
            "items": [
              "salamat",
              "sige"
            ]
          },
          {
            "id": "cu1a1",
            "title": "Hello, How Are You?",
            "kind": "apply",
            "items": [
              "Maupay nga aga!",
              "Maupay nga gab-i.",
              "Kamusta ikaw?",
              "Ako hi Ana.",
              "Salamat.",
              "Sige."
            ]
          }
        ],
        "story": {
          "id": "u1s1",
          "title": "Bag-o nga Adlaw",
          "titleEn": "A New Day",
          "lines": [
            {
              "war": "Maupay nga aga!",
              "en": "Good morning!"
            },
            {
              "war": "Ako hi Maria.",
              "en": "I am Maria."
            },
            {
              "war": "Kamusta ikaw?",
              "en": "How are you?"
            },
            {
              "war": "Maupay nga kulop.",
              "en": "Good afternoon."
            },
            {
              "war": "Salamat.",
              "en": "Thanks."
            },
            {
              "war": "Maupay nga gab-i.",
              "en": "Good evening."
            },
            {
              "war": "Sige.",
              "en": "Okay."
            }
          ],
          "q": {
            "q": "What does 'Maupay nga aga' mean?",
            "options": [
              "Good afternoon",
              "Good morning",
              "Good night"
            ],
            "answer": 1
          }
        }
      },
      {
        "id": "cu2",
        "name": "Hain an Balay?",
        "hint": "Location & Family",
        "lessons": [
          {
            "id": "cu2l1",
            "title": "Where Is It?",
            "items": [
              "hain",
              "aadi",
              "aada",
              "didto"
            ]
          },
          {
            "id": "cu2l2",
            "title": "He, She, Not",
            "items": [
              "hiya",
              "diri",
              "dadi"
            ]
          },
          {
            "id": "cu2l3",
            "title": "My Family",
            "items": [
              "nanay",
              "tatay",
              "asawa",
              "anak"
            ]
          },
          {
            "id": "cu2l4",
            "title": "More",
            "items": [
              "balay",
              "Balite"
            ]
          },
          {
            "id": "cu2a1",
            "title": "Finding Balay",
            "kind": "apply",
            "items": [
              "Hain hi Nanay?",
              "Aadi hiya.",
              "Diri hiya aadi.",
              "Aada an balay.",
              "Didto ha Balite.",
              "Dadi, anak ko!"
            ]
          }
        ],
        "story": {
          "id": "u2s1",
          "title": "An Balay ni Tatay",
          "titleEn": "Father's House",
          "lines": [
            {
              "war": "Hain hi Tatay?",
              "en": "Where is Dad?"
            },
            {
              "war": "Aadi hiya ha balay.",
              "en": "He is here at the house."
            },
            {
              "war": "Diri hiya aada.",
              "en": "He is not there (near you)."
            },
            {
              "war": "An anak ni Tatay aadi.",
              "en": "Father's child is here."
            },
            {
              "war": "Hain an asawa?",
              "en": "Where is the spouse?"
            },
            {
              "war": "Didto hiya ha Balite.",
              "en": "He/she is over there in Balite."
            }
          ],
          "q": {
            "q": "Where is Tatay?",
            "options": [
              "He is at the house.",
              "He is in Balite.",
              "He is not here."
            ],
            "answer": 0
          }
        }
      },
      {
        "id": "cu3",
        "name": "Gusto Ko Tubig",
        "hint": "Wants & Needs (Food/Drink)",
        "lessons": [
          {
            "id": "cu3l1",
            "title": "What Do You Want?",
            "items": [
              "gusto",
              "tubig",
              "kape"
            ]
          },
          {
            "id": "cu3l2",
            "title": "Eat and Drink",
            "items": [
              "kaon",
              "inom",
              "kan-on"
            ]
          },
          {
            "id": "cu3l3",
            "title": "Polite Responses",
            "items": [
              "alayon",
              "oo"
            ]
          },
          {
            "id": "cu3a1",
            "title": "At the Table",
            "kind": "apply",
            "items": [
              "Gusto ko tubig.",
              "Gusto mo kape?",
              "Oo, gusto ko kape.",
              "Alayon, kan-on.",
              "Kaon na.",
              "Inom tubig."
            ]
          }
        ],
        "story": {
          "id": "u3s1",
          "title": "Pagkaon ha Aga",
          "titleEn": "Food in the Morning",
          "lines": [
            {
              "war": "Maupay nga aga!",
              "en": "Good morning!"
            },
            {
              "war": "Gusto mo kape?",
              "en": "Do you want coffee?"
            },
            {
              "war": "Oo, gusto ko kape.",
              "en": "Yes, I want coffee."
            },
            {
              "war": "Alayon, kan-on.",
              "en": "Please, cooked rice."
            },
            {
              "war": "Kaon, anak.",
              "en": "Eat, child."
            },
            {
              "war": "Inom tubig, Tatay.",
              "en": "Drink water, Dad."
            },
            {
              "war": "Salamat.",
              "en": "Thanks."
            }
          ],
          "q": {
            "q": "What does the speaker want?",
            "options": [
              "Water and rice",
              "Coffee and rice",
              "Coffee and water"
            ],
            "answer": 1
          }
        }
      },
      {
        "id": "cu4",
        "name": "Akon nga Balay",
        "hint": "Possessions & Singular Pronouns",
        "lessons": [
          {
            "id": "cu4l1",
            "title": "My, Your, His/Her (Pre-posed)",
            "items": [
              "akon",
              "imo",
              "iya"
            ]
          },
          {
            "id": "cu4l2",
            "title": "My, Your, His/Her (Enclitic)",
            "items": [
              "ko",
              "mo",
              "na"
            ]
          },
          {
            "id": "cu4a1",
            "title": "Whose Is It?",
            "kind": "apply",
            "items": [
              "Akon balay ini.",
              "Imo ba ini nga kape?",
              "Oo, kape ko ini.",
              "An anak na aada.",
              "Gusto ko an imo tubig.",
              "Gusto niya kan-on."
            ]
          }
        ],
        "story": {
          "id": "u4s1",
          "title": "An Amon mga Butang",
          "titleEn": "Our Things",
          "lines": [
            {
              "war": "Maupay nga aga, Tatay!",
              "en": "Good morning, Dad!"
            },
            {
              "war": "Akon nga kape ini.",
              "en": "This is my coffee."
            },
            {
              "war": "Hain an imo kan-on?",
              "en": "Where is your cooked rice?"
            },
            {
              "war": "Aada an kan-on mo.",
              "en": "Your cooked rice is there."
            },
            {
              "war": "Gusto ni Nanay an iya tubig.",
              "en": "Mom wants her water."
            },
            {
              "war": "Inom na, anak.",
              "en": "Drink now, child."
            }
          ],
          "q": {
            "q": "Whose coffee is mentioned?",
            "options": [
              "The father's",
              "The speaker's",
              "The mother's"
            ],
            "answer": 1
          }
        }
      },
      {
        "id": "cu5",
        "name": "Pira Ini?",
        "hint": "Numbers, Buying & Prices",
        "lessons": [
          {
            "id": "cu5l1",
            "title": "Counting 1-3",
            "items": [
              "usa",
              "duha",
              "tulo"
            ]
          },
          {
            "id": "cu5l2",
            "title": "More Numbers & How Many?",
            "items": [
              "upat",
              "lima",
              "pira"
            ]
          },
          {
            "id": "cu5l3",
            "title": "Buying & Prices",
            "items": [
              "tagpira",
              "palit",
              "mapalit",
              "pesos"
            ]
          },
          {
            "id": "cu5a1",
            "title": "At the Tindahan (Store)",
            "kind": "apply",
            "items": [
              "Pira nga tubig?",
              "Usa nga tubig.",
              "Tagpira an kape?",
              "Lima ka pesos.",
              "Mapalit ako duha nga kape.",
              "Salamat, Tatay."
            ]
          }
        ],
        "story": {
          "id": "u5s1",
          "title": "Pamalit ha Tindahan",
          "titleEn": "Buying at the Store",
          "lines": [
            {
              "war": "Maupay nga kulop!",
              "en": "Good afternoon!"
            },
            {
              "war": "Mapalit ako tubig.",
              "en": "I will buy water."
            },
            {
              "war": "Pira nga tubig?",
              "en": "How many waters?"
            },
            {
              "war": "Duha nga tubig.",
              "en": "Two waters."
            },
            {
              "war": "Tagpira an usa?",
              "en": "How much is one (each)?"
            },
            {
              "war": "Tulo ka pesos.",
              "en": "Three pesos."
            },
            {
              "war": "Sige, salamat.",
              "en": "Okay, thanks."
            }
          ],
          "q": {
            "q": "How many waters will the person buy?",
            "options": [
              "One",
              "Two",
              "Three"
            ],
            "answer": 1
          }
        }
      },
      {
        "id": "cu6",
        "name": "Yana nga Adlaw",
        "hint": "Time Expressions",
        "lessons": [
          {
            "id": "cu6l1",
            "title": "Now and Today",
            "items": [
              "yana",
              "udto",
              "adlaw"
            ]
          },
          {
            "id": "cu6l2",
            "title": "Past and Future Time",
            "items": [
              "kahapon",
              "buwas",
              "san-o"
            ]
          },
          {
            "id": "cu6a1",
            "title": "When Will We Eat?",
            "kind": "apply",
            "items": [
              "Kaon yana.",
              "Mapalit ako buwas.",
              "San-o ka inom kape?",
              "Nag-inom ako kahapon.",
              "Ha udto an kaon.",
              "Yana nga gab-i."
            ]
          }
        ],
        "story": {
          "id": "u6s1",
          "title": "Mga Plano",
          "titleEn": "Plans",
          "lines": [
            {
              "war": "Maupay nga adlaw!",
              "en": "Good day!"
            },
            {
              "war": "San-o ka mapalit tubig?",
              "en": "When will you buy water?"
            },
            {
              "war": "Mapalit ako buwas.",
              "en": "I will buy tomorrow."
            },
            {
              "war": "Kaon kita yana nga udto.",
              "en": "Let's eat this noon."
            },
            {
              "war": "Nag-inom hiya kape kahapon.",
              "en": "He/she drank coffee yesterday."
            },
            {
              "war": "Sige, salamat.",
              "en": "Okay, thanks."
            }
          ],
          "q": {
            "q": "When will the speaker buy water?",
            "options": [
              "Today",
              "Tomorrow",
              "Yesterday"
            ],
            "answer": 1
          }
        }
      },
      {
        "id": "cu7",
        "name": "Kita Ngan Kamo",
        "hint": "Plural Pronouns & Group Actions",
        "lessons": [
          {
            "id": "cu7l1",
            "title": "We, You All, They (Independent)",
            "items": [
              "kita",
              "kami",
              "kamo",
              "hira"
            ]
          },
          {
            "id": "cu7l2",
            "title": "Our, Your, Their (Pre-posed)",
            "items": [
              "aton",
              "amon",
              "iyo",
              "ira"
            ]
          },
          {
            "id": "cu7l3",
            "title": "Our, Your, Their (Enclitic)",
            "items": [
              "ta",
              "mi",
              "niyo",
              "nira"
            ]
          },
          {
            "id": "cu7a1",
            "title": "Group Activities",
            "kind": "apply",
            "items": [
              "Kaon kita yana.",
              "Kami mapalit tubig.",
              "Kamusta kamo?",
              "Iyo balay ini.",
              "Gusto nira kape.",
              "Amon mga anak."
            ]
          }
        ],
        "story": {
          "id": "u7s1",
          "title": "An Pamilya",
          "titleEn": "The Family",
          "lines": [
            {
              "war": "Maupay nga aga, kamo!",
              "en": "Good morning, everyone!"
            },
            {
              "war": "Mapalit kami kan-on buwas.",
              "en": "We (not you) will buy cooked rice tomorrow."
            },
            {
              "war": "Kaon kita yana nga udto.",
              "en": "Let's eat this noon (you and I)."
            },
            {
              "war": "Hain an iyo balay?",
              "en": "Where is your (plural) house?"
            },
            {
              "war": "Didto an ira balay ha Balite.",
              "en": "Their house is over there in Balite."
            },
            {
              "war": "An tubig nira didto.",
              "en": "Their water is over there."
            },
            {
              "war": "Salamat ha iyo.",
              "en": "Thanks to you all."
            }
          ],
          "q": {
            "q": "Who will buy cooked rice tomorrow?",
            "options": [
              "The speaker and listener",
              "The speaker and others (not listener)",
              "The listener and others"
            ],
            "answer": 1
          }
        }
      }
    ]
  },
  {
    "id": "cp2",
    "name": "Daily Life in the Neighborhood",
    "hint": "In-laws, the yard, going places, weather, and daily times",
    "units": [
      {
        "id": "cu6",
        "name": "Meeting the In-Laws",
        "hint": "Introduce yourself respectfully to extended family",
        "lessons": [
          {
            "id": "cu6l1",
            "title": "Respectful Titles",
            "items": [
              "apo",
              "mano",
              "mana"
            ]
          },
          {
            "id": "cu6l2",
            "title": "Glad to Meet You",
            "items": [
              "bana",
              "nalipay",
              "kila"
            ]
          }
        ],
        "story": {
          "id": "cu6s1",
          "title": "Ha Balay han In-laws",
          "titleEn": "At the In-laws' House",
          "lines": [
            {
              "war": "Maupay nga kulop, Apo.",
              "en": "Good afternoon, Grandparent."
            },
            {
              "war": "Ako hi Tom, an bana ni Maria.",
              "en": "I am Tom, the husband of Maria."
            },
            {
              "war": "Kumusta, Mana Elena ngan Mano Lito?",
              "en": "How are you, Older Sister Elena and Older Brother Lito?"
            },
            {
              "war": "Nalipay ako makakila ha iyo.",
              "en": "I am happy to meet you all."
            }
          ],
          "q": {
            "q": "Who is Tom introducing himself to?",
            "options": [
              "His neighbors",
              "His wife's extended family",
              "Store owners"
            ],
            "answer": 1
          }
        }
      },
      {
        "id": "cu7",
        "name": "Objects in the Yard",
        "hint": "Ask for everyday household items",
        "lessons": [
          {
            "id": "cu7l1",
            "title": "Around the Yard",
            "items": [
              "lingkuran",
              "lamesa",
              "brayong"
            ]
          },
          {
            "id": "cu7l2",
            "title": "Kitchen Things",
            "items": [
              "banga",
              "kutsara",
              "tinidor",
              "kadi"
            ]
          }
        ],
        "story": {
          "id": "cu7s1",
          "title": "Ha Gawas han Balay",
          "titleEn": "Outside the House",
          "lines": [
            {
              "war": "Hain an aton lingkuran, Maria?",
              "en": "Where is our chair, Maria?"
            },
            {
              "war": "Aada ha gawas, dapit ha lamesa.",
              "en": "It is there outside, near the table."
            },
            {
              "war": "Tom, alayon kadi an brayong.",
              "en": "Tom, please bring the broom here."
            },
            {
              "war": "Gusto ko uminom han tubig tikang ha banga.",
              "en": "I want to drink water from the clay jar."
            }
          ],
          "q": {
            "q": "Where is the chair located?",
            "options": [
              "Inside the kitchen",
              "Outside, near the table",
              "At the neighbor's house"
            ],
            "answer": 1
          }
        }
      },
      {
        "id": "cu8",
        "name": "Where Are You Going?",
        "hint": "Answer the passing greeting 'Kain ka?'",
        "lessons": [
          {
            "id": "cu8l1",
            "title": "Kain ka?",
            "items": [
              "kain",
              "madto",
              "pakadto"
            ]
          },
          {
            "id": "cu8l2",
            "title": "Local Destinations",
            "items": [
              "tindahan",
              "pantalan",
              "uma"
            ]
          }
        ],
        "story": {
          "id": "cu8s1",
          "title": "Kinasasandat ha Dalan",
          "titleEn": "Meeting on the Street",
          "lines": [
            {
              "war": "Maupay nga aga, Tom! Kain ka?",
              "en": "Good morning, Tom! Where are you heading?"
            },
            {
              "war": "Maupay nga aga! Madto ako ha tindahan.",
              "en": "Good morning! I am going to the store."
            },
            {
              "war": "Ikaw, kain ka pakadto?",
              "en": "As for you, where are you heading towards?"
            },
            {
              "war": "Pakadto ako ha pantalan han Daram.",
              "en": "I am heading towards the Daram pier."
            }
          ],
          "q": {
            "q": "What does the greeting 'Kain ka?' mean?",
            "options": [
              "How are you?",
              "Where are you going?",
              "Have you eaten yet?"
            ],
            "answer": 1
          }
        }
      },
      {
        "id": "cu9",
        "name": "The Weather",
        "hint": "Comment on heat, rain, and wind",
        "lessons": [
          {
            "id": "cu9l1",
            "title": "Island Heat",
            "items": [
              "mapaso",
              "kamapas",
              "masyado"
            ]
          },
          {
            "id": "cu9l2",
            "title": "Rain & Wind",
            "items": [
              "uran",
              "umuuran",
              "hangin",
              "mahagkot"
            ]
          }
        ],
        "story": {
          "id": "cu9s1",
          "title": "An Panahon ha Daram",
          "titleEn": "The Weather in Daram",
          "lines": [
            {
              "war": "Masyado mapaso yana nga aga.",
              "en": "It is very hot this morning."
            },
            {
              "war": "Oo, kamapas han hangin didni.",
              "en": "Yes, the air is humid right here."
            },
            {
              "war": "Aadi an uran! Umuuran na.",
              "en": "Here comes the rain! It is raining now."
            },
            {
              "war": "Mahagkot an tubig yana.",
              "en": "The water is cold now."
            }
          ],
          "q": {
            "q": "What happens to the weather during the conversation?",
            "options": [
              "It stays dry and hot",
              "It begins to rain",
              "It turns completely dark"
            ],
            "answer": 1
          }
        }
      },
      {
        "id": "cu10",
        "name": "Time & Simple Tasks",
        "hint": "Coordinate daily times and chores",
        "lessons": [
          {
            "id": "cu10l1",
            "title": "Today & Tomorrow",
            "items": [
              "yana",
              "buwas",
              "nganay"
            ]
          },
          {
            "id": "cu10l2",
            "title": "Chores & Rest",
            "items": [
              "buhat",
              "trabaho",
              "pahuway"
            ]
          }
        ],
        "story": {
          "id": "cu10s1",
          "title": "An Plano Buwas",
          "titleEn": "The Plan for Tomorrow",
          "lines": [
            {
              "war": "Mano Lito, may trabaho ba yana?",
              "en": "Older Brother Lito, is there work today?"
            },
            {
              "war": "Diri, pahuway nganay kita yana nga kulop.",
              "en": "No, let's rest for a moment this afternoon."
            },
            {
              "war": "An brayong dadi, magbuhat ako buwas.",
              "en": "The broom is here; I will do the tasks tomorrow."
            },
            {
              "war": "Maupay hira, mapahuway gihapon ako.",
              "en": "Good for them; I will rest as well."
            }
          ],
          "q": {
            "q": "When will the tasks be done?",
            "options": [
              "Today",
              "Tomorrow",
              "In the evening"
            ],
            "answer": 1
          }
        }
      },
      {
        "id": "cu11",
        "name": "Review & Celebration",
        "hint": "Mix neighborhood conversations smoothly",
        "lessons": [
          {
            "id": "cu11l1",
            "title": "Neighborhood Mix A",
            "items": [
              "kamusta",
              "apo",
              "kain",
              "madto",
              "tindahan",
              "yana"
            ]
          },
          {
            "id": "cu11l2",
            "title": "Neighborhood Mix B",
            "items": [
              "mapaso",
              "uran",
              "lingkuran",
              "banga",
              "buwas",
              "pahuway"
            ]
          }
        ],
        "story": {
          "id": "cu11s1",
          "title": "Hurob-hurob ha Daram",
          "titleEn": "Chitchatting in Daram",
          "lines": [
            {
              "war": "Maupay nga aga, Mana Elena! Kain ka pakadto?",
              "en": "Good morning, Older Sister Elena! Where are you heading?"
            },
            {
              "war": "Madto ako ha pantalan, Tom. Masyado mapaso yana.",
              "en": "I am going to the pier, Tom. It is very hot today."
            },
            {
              "war": "Oo, kadi nganay ha aton lingkuran han balay.",
              "en": "Yes, come over for a moment to our chair at the house."
            },
            {
              "war": "Alayon, uminom kita hin tubig tikang ha banga.",
              "en": "Please, let's drink water from the clay jar."
            },
            {
              "war": "Nalipay gihapon hi Apo didto.",
              "en": "Grandparent over there was glad too."
            }
          ],
          "q": {
            "q": "What refreshing invitation is offered?",
            "options": [
              "To go to the farm",
              "To buy something at the store",
              "To sit and drink water from the clay jar"
            ],
            "answer": 2
          }
        }
      }
    ]
  }
];

// CEFR tag per Challenger-only WORD (single tokens only; phrases excluded).
// Phase 1 decks ch1–ch7 = A0; Phase 2 decks ch8–ch12 = A1.
const CH_P1_DECKS = new Set(["ch1","ch2","ch3","ch4","ch5","ch6","ch7"]);
export const CH_LEVELS = {};
for (const r of SEED_CH) { if (!/\s/.test(r[1])) CH_LEVELS[r[1]] = CH_P1_DECKS.has(r[0]) ? "A0" : "A1"; }
