/* Waray (Challenger 2 · Daram — EXPANDED) — GENERATED by tools/build-challenger2.mjs.
   The denser 8-10-words/lesson redesign (Gemini API, self-audited + patched), kept as a
   SEPARATE course so it can run side-by-side with the original Challenger. Phase 1 only.
   Card shape: [deck, waray, english, subtext, respelling, example?]. Decks c2u1..c2u5. */

export const SEED_CH2 = [
  ["c2u1","maupay","good","","",{"war":"Maupay nga aga","focus":"Maupay","en":"Good morning"}],
  ["c2u1","aga","morning","","",{"war":"Maupay nga aga","focus":"aga","en":"Good morning"}],
  ["c2u1","udto","noon","","",{"war":"Maupay nga udto","focus":"udto","en":"Good noon"}],
  ["c2u1","kulop","afternoon","","",{"war":"Maupay nga kulop","focus":"kulop","en":"Good afternoon"}],
  ["c2u1","gab-i","evening/night","","",{"war":"Maupay nga gab-i","focus":"gab-i","en":"Good evening"}],
  ["c2u1","yana","now","","",{"war":"Maupay kita yana","focus":"yana","en":"We are good now"}],
  ["c2u1","kaina","earlier (today)","","",{"war":"Maupay hira kaina","focus":"kaina","en":"They were good earlier"}],
  ["c2u1","unina","later (today)","","",{"war":"Maupay ako unina","focus":"unina","en":"I'll be good later"}],
  ["c2u1","kamusta","how are you","","",{"war":"Kamusta ikaw?","focus":"Kamusta","en":"How are you?"}],
  ["c2u1","ako","I","","",{"war":"Ako hi Maria","focus":"Ako","en":"I am Maria"}],
  ["c2u1","ikaw","you (sg)","","",{"war":"Kamusta ikaw?","focus":"ikaw","en":"How are you?"}],
  ["c2u1","hiya","he/she","","",{"war":"Maupay hiya","focus":"hiya","en":"He/she is good"}],
  ["c2u1","hira","they","","",{"war":"Maupay hira","focus":"hira","en":"They are good"}],
  ["c2u1","kami","we (exclusive)","","",{"war":"Maupay kami","focus":"kami","en":"We are good (not including you)"}],
  ["c2u1","kita","we (inclusive)","","",{"war":"Maupay kita","focus":"kita","en":"We are good (including you)"}],
  ["c2u1","Maupay nga aga, hi Maria.","Good morning, Maria.","","",null],
  ["c2u1","Kamusta ikaw yana?","How are you now?","","",null],
  ["c2u1","Maupay ako yana.","I am good now.","","",null],
  ["c2u1","Maupay hira kaina.","They were good earlier.","","",null],
  ["c2u1","Maupay kita unina!","We'll be good later (you and I)!","","",null],
  ["c2u1","Maupay nga gab-i, hi Juan.","Good evening, Juan.","","",null],
  ["c2u1","Kamusta hira? Maupay kami.","How are they? We're good (not you).","","",null],
  ["c2u1","Maupay kita yana.","We are good now (you and I).","","",null],
  ["c2u2","nanay","mother","","",{"war":"Maupay hi nanay.","focus":"nanay","en":"Mother is good."}],
  ["c2u2","tatay","father","","",{"war":"Aadi hi tatay.","focus":"tatay","en":"Father is here."}],
  ["c2u2","kuya","older brother — also any slightly older male","","",{"war":"Kuya, dadi!","focus":"kuya","en":"Older brother, come here!"}],
  ["c2u2","ate","older sister — also any slightly older female","","",{"war":"Ate, hain ka?","focus":"ate","en":"Older sister, where are you?"}],
  ["c2u2","bugto","sibling","","",{"war":"Hiya an bugto ko.","focus":"bugto","en":"He/she is my sibling."}],
  ["c2u2","asawa","spouse","","",{"war":"Aada an asawa mo.","focus":"asawa","en":"Your spouse is there."}],
  ["c2u2","anak","child","","",{"war":"Anak ko hiya.","focus":"anak","en":"He/she is my child."}],
  ["c2u2","apo","grandchild","","",{"war":"Didto an apo ko.","focus":"apo","en":"My grandchild is over there."}],
  ["c2u2","aadi","here","","",{"war":"Aadi hiya.","focus":"aadi","en":"He/she is here."}],
  ["c2u2","aada","there","","",{"war":"Aada an kape.","focus":"aada","en":"The coffee is there."}],
  ["c2u2","didto","over there","","",{"war":"Didto an balay.","focus":"didto","en":"The house is over there."}],
  ["c2u2","hain","where","","",{"war":"Hain hi nanay?","focus":"hain","en":"Where is mother?"}],
  ["c2u2","oo","yes","","",{"war":"Oo, maupay ako.","focus":"oo","en":"Yes, I am good."}],
  ["c2u2","diri","no/not","","",{"war":"Diri hiya maupay.","focus":"diri","en":"He/she is not good."}],
  ["c2u2","dadi","come here","","",{"war":"Dadi, anak ko.","focus":"dadi","en":"Come here, my child."}],
  ["c2u2","ngadto","go there","","",{"war":"Ngadto hiya.","focus":"ngadto","en":"He/she goes there."}],
  ["c2u2","Hain hi tatay mo?","Where is your father?","","",null],
  ["c2u2","Aadi hi nanay.","Mother is here.","","",null],
  ["c2u2","Aada hi kuya.","Older brother is there.","","",null],
  ["c2u2","Didto hi ate.","Older sister is over there.","","",null],
  ["c2u2","Diri hiya an bugto ko.","He/she is not my sibling.","","",null],
  ["c2u2","Oo, dadi hi anak ko.","Yes, my child, come here.","","",null],
  ["c2u2","Hain hi asawa mo?","Where is your spouse?","","",null],
  ["c2u2","Diri hiya aadi, ngadto hiya.","He/she is not here, he/she goes there.","","",null],
  ["c2u2","Aada hi apo ko, dadi!","My grandchild is there, come here!","","",null],
  ["c2u2","Oo, hi nanay ko aadi.","Yes, my mother is here.","","",null],
  ["c2u3","balay","house","","",{"war":"in balay","focus":"balay","en":"the house"}],
  ["c2u3","kwarto","room","","",{"war":"in kwarto","focus":"kwarto","en":"the room"}],
  ["c2u3","kusina","kitchen","","",{"war":"in kusina","focus":"kusina","en":"the kitchen"}],
  ["c2u3","pantaw","back porch","Wash area common in Samar homes.","",{"war":"ha pantaw","focus":"pantaw","en":"on the back porch"}],
  ["c2u3","purtahan","door","","",{"war":"in purtahan","focus":"purtahan","en":"the door"}],
  ["c2u3","bintana","window","","",{"war":"in bintana","focus":"bintana","en":"the window"}],
  ["c2u3","natad","yard","","",{"war":"ha natad","focus":"natad","en":"in the yard"}],
  ["c2u3","kudal","fence","","",{"war":"in kudal","focus":"kudal","en":"the fence"}],
  ["c2u3","akon","my/mine","","",{"war":"Akon balay","focus":"Akon","en":"My house"}],
  ["c2u3","imo","your/yours (sg)","","",{"war":"Imo kwarto","focus":"Imo","en":"Your room"}],
  ["c2u3","iyo","your/yours (pl)","","",{"war":"Iyo kusina","focus":"Iyo","en":"Your kitchen (plural)"}],
  ["c2u3","sulod","enter","","",{"war":"Sulod ha balay","focus":"Sulod","en":"Enter the house"}],
  ["c2u3","gawas","exit / go out","","",{"war":"Gawas ha natad","focus":"Gawas","en":"Go out to the yard"}],
  ["c2u3","lingkod","sit","","",{"war":"Lingkod didto","focus":"Lingkod","en":"Sit there"}],
  ["c2u3","tindog","stand","","",{"war":"Tindog yana","focus":"Tindog","en":"Stand now"}],
  ["c2u3","Sulod ha kwarto.","Enter the room.","","",null],
  ["c2u3","Lingkod ha pantaw.","Sit on the back porch.","","",null],
  ["c2u3","Imo balay ini.","This is your house.","","",null],
  ["c2u3","Gawas ha natad.","Go out to the yard.","","",null],
  ["c2u3","Akon kusina adto.","That is my kitchen.","","",null],
  ["c2u3","Tindog ha purtahan.","Stand at the door.","","",null],
  ["c2u3","Iyo bintana adto.","That is your (plural) window.","","",null],
  ["c2u3","in kudal","the fence","","",null],
  ["c2u3","Sulod ha balay, akon anak.","Enter the house, my friend.","","",null],
  ["c2u4","tubig","water","","",{"war":"Inom hin tubig.","focus":"tubig","en":"Drink some water."}],
  ["c2u4","kape","coffee","","",{"war":"Gusto ko kape.","focus":"kape","en":"I want coffee."}],
  ["c2u4","kan-on","cooked rice","","",{"war":"Kaon hin kan-on.","focus":"kan-on","en":"Eat some rice."}],
  ["c2u4","isda","fish","","",{"war":"Gusto ko isda.","focus":"isda","en":"I want fish."}],
  ["c2u4","utan","vegetables","","",{"war":"Kaon hin utan.","focus":"utan","en":"Eat some vegetables."}],
  ["c2u4","prutas","fruit","","",{"war":"Gusto ko prutas.","focus":"prutas","en":"I want fruit."}],
  ["c2u4","tinapay","bread","","",{"war":"Gusto mo tinapay?","focus":"tinapay","en":"Do you want bread?"}],
  ["c2u4","sabaw","soup/broth","","",{"war":"Init nga sabaw.","focus":"sabaw","en":"Hot soup."}],
  ["c2u4","gusto","want","","",{"war":"Gusto ko tubig.","focus":"Gusto","en":"I want water."}],
  ["c2u4","kinahanglan","need","","",{"war":"Kinahanglan ko tubig.","focus":"Kinahanglan","en":"I need water."}],
  ["c2u4","alayon","please","","",{"war":"Alayon, tubig.","focus":"Alayon","en":"Please, water."}],
  ["c2u4","salamat","thank you","","",{"war":"Salamat, amigo.","focus":"Salamat","en":"Thank you, friend."}],
  ["c2u4","kaon","eat","","",{"war":"Kaon hin isda.","focus":"Kaon","en":"Eat some fish."}],
  ["c2u4","inom","drink","","",{"war":"Inom hin kape.","focus":"Inom","en":"Drink some coffee."}],
  ["c2u4","init","hot","","",{"war":"Init nga kape.","focus":"init","en":"Hot coffee."}],
  ["c2u4","matugnaw","cold","","",{"war":"Matugnaw nga tubig.","focus":"matugnaw","en":"Cold water."}],
  ["c2u4","ko","my / by me (enclitic)","Post-posed agent/possessor of ako.","",{"war":"Kape ko","focus":"ko","en":"My coffee"}],
  ["c2u4","mo","your / by you (enclitic)","Post-posed agent/possessor of ikaw.","",{"war":"Gusto mo?","focus":"mo","en":"Do you want it?"}],
  ["c2u4","niya","his/her / by him-her","Agent/possessor of hiya — confirm Daram form.","",{"war":"Gusto niya isda","focus":"niya","en":"He/she wants fish"}],
  ["c2u4","Gusto ko hin init nga kape.","I want some hot coffee.","","",null],
  ["c2u4","Kinahanglan ko hin tubig, alayon.","I need some water, please.","","",null],
  ["c2u4","Kaon hin isda ngan utan.","Eat some fish and vegetables.","","",null],
  ["c2u4","Gusto mo matugnaw nga prutas?","Do you want cold fruit?","","",null],
  ["c2u4","Inom sin sabaw.","Drink some soup.","","",null],
  ["c2u4","Salamat, gusto ko hin kan-on.","Thank you, I want some rice.","","",null],
  ["c2u4","Alayon, gusto ko hin tinapay.","Please, I want some bread.","","",null],
  ["c2u4","Kinahanglan mo ba matugnaw nga tubig?","Do you need cold water?","","",null],
  ["c2u4","Kaon hin prutas ngan inom hin tubig.","Eat fruit and drink water.","","",null],
  ["c2u5","usa","one","","",{"war":"usa ka isda","focus":"usa","en":"one mango"}],
  ["c2u5","duha","two","","",{"war":"duha ka isda","focus":"duha","en":"two fish"}],
  ["c2u5","tulo","three","","",{"war":"tulo ka tinapay","focus":"tulo","en":"three tomatoes"}],
  ["c2u5","upat","four","","",{"war":"upat ka isda","focus":"upat","en":"four bananas"}],
  ["c2u5","lima","five","","",{"war":"lima ka tinapay","focus":"lima","en":"five eggs"}],
  ["c2u5","unom","six","","",{"war":"unom ka anak","focus":"unom","en":"six young coconuts"}],
  ["c2u5","pito","seven","","",{"war":"pito ka tinapay","focus":"pito","en":"seven watermelons"}],
  ["c2u5","walo","eight","","",{"war":"walo ka tinapay","focus":"walo","en":"eight breads"}],
  ["c2u5","siyam","nine","","",{"war":"siyam ka isda","focus":"siyam","en":"nine mangoes"}],
  ["c2u5","napulo","ten","","",{"war":"napulo ka isda","focus":"napulo","en":"ten fish"}],
  ["c2u5","pira","how many","","",{"war":"Pira an isda?","focus":"Pira","en":"How many fish?"}],
  ["c2u5","tagpira","how much each","","",{"war":"Tagpira ini?","focus":"Tagpira","en":"How much is this?"}],
  ["c2u5","palit","buy","","",{"war":"Gusto ko magpalit","focus":"palit","en":"I want to buy"}],
  ["c2u5","mapalit","will buy","","",{"war":"Mapalit ako isda","focus":"mapalit","en":"I will buy fish"}],
  ["c2u5","bayad","pay","","",{"war":"Bayad na!","focus":"Bayad","en":"Pay now!"}],
  ["c2u5","sukli","change (money)","","",{"war":"Waray sukli?","focus":"sukli","en":"No change?"}],
  ["c2u5","kwarta","money","","",{"war":"Akon kwarta ako","focus":"kwarta","en":"I have money"}],
  ["c2u5","pesos","pesos","","",{"war":"lima ka pesos","focus":"pesos","en":"five pesos"}],
  ["c2u5","mahal","expensive","","",{"war":"Mahal ini.","focus":"Mahal","en":"This is expensive."}],
  ["c2u5","barato","cheap","","",{"war":"Barato ini.","focus":"Barato","en":"This is cheap."}],
  ["c2u5","Tagpira ini nga isda?","How much is this fish?","","",null],
  ["c2u5","Lima ka pesos.","Five pesos.","","",null],
  ["c2u5","Mapalit ako tulo ka isda.","I will buy three mangoes.","","",null],
  ["c2u5","Mahal ini.","This is expensive.","","",null],
  ["c2u5","Barato an isda.","The banana is cheap.","","",null],
  ["c2u5","Waray ako sukli.","I don't have change.","","",null],
  ["c2u5","Pira an kwarta mo?","How much is your money?","","",null],
  ["c2u5","Mapalit ka napulo ka tinapay?","Will you buy ten eggs?","","",null],
  ["c2u5","Bayad na! Waray sukli.","Pay now! No change.","","",null],
  ["c2u5","Mahal ini nga isda, barato an isda.","This fish is expensive, the banana is cheap.","","",null],
];

export const FORGOTTEN_CH2 = new Set();

export const CHALLENGER2 = [
  {
    "id": "c2p1",
    "name": "First Steps in Daram (Expanded)",
    "hint": "Denser greetings, family, home, food, numbers — the expanded build",
    "units": [
      {
        "id": "u1",
        "name": "Greetings, Time, and Pronouns",
        "hint": "Basic Social Encounters",
        "lessons": [
          {
            "id": "u1l1",
            "title": "Times of Day",
            "items": [
              "maupay",
              "aga",
              "udto",
              "kulop",
              "gab-i",
              "yana",
              "kaina",
              "unina"
            ]
          },
          {
            "id": "u1l2",
            "title": "Pronouns & Identity",
            "items": [
              "kamusta",
              "ako",
              "ikaw",
              "hiya",
              "hira",
              "kami",
              "kita"
            ]
          },
          {
            "id": "u1l3",
            "title": "Putting it Together",
            "kind": "apply",
            "items": [
              "Maupay nga aga, hi Maria.",
              "Kamusta ikaw yana?",
              "Maupay ako yana.",
              "Maupay hira kaina.",
              "Maupay kita unina!"
            ]
          },
          {
            "id": "u1l4",
            "title": "Unit u1 Review",
            "kind": "apply",
            "items": [
              "Maupay nga gab-i, hi Juan.",
              "Kamusta hira? Maupay kami.",
              "Maupay kita yana."
            ]
          }
        ],
        "story": {
          "id": "u1s1",
          "title": "Kamusta Kita?",
          "titleEn": "How Are We?",
          "lines": [
            {
              "war": "Maupay nga aga. Ako hi Maria.",
              "en": "Good morning. I am Maria."
            },
            {
              "war": "Kamusta ikaw yana?",
              "en": "How are you now?"
            },
            {
              "war": "Maupay ako. Maupay kita yana!",
              "en": "I am good. We are good now!"
            }
          ],
          "q": {
            "q": "What time of day is it?",
            "options": [
              "Morning",
              "Noon",
              "Evening"
            ],
            "answer": 0
          }
        }
      },
      {
        "id": "u2",
        "name": "Family, Respect, and Pointers",
        "hint": "Basic Locations and Relatives",
        "lessons": [
          {
            "id": "u2l1",
            "title": "Family Members",
            "items": [
              "nanay",
              "tatay",
              "kuya",
              "ate",
              "bugto",
              "asawa",
              "anak",
              "apo"
            ]
          },
          {
            "id": "u2l2",
            "title": "Pointers and Negation",
            "items": [
              "aadi",
              "aada",
              "didto",
              "hain",
              "oo",
              "diri",
              "dadi",
              "ngadto"
            ]
          },
          {
            "id": "u2l3",
            "title": "Finding Family and Places",
            "kind": "apply",
            "items": [
              "Hain hi tatay mo?",
              "Aadi hi nanay.",
              "Aada hi kuya.",
              "Didto hi ate.",
              "Diri hiya an bugto ko.",
              "Oo, dadi hi anak ko."
            ]
          },
          {
            "id": "u2l4",
            "title": "Unit u2 Review",
            "kind": "apply",
            "items": [
              "Hain hi asawa mo?",
              "Diri hiya aadi, ngadto hiya.",
              "Aada hi apo ko, dadi!",
              "Oo, hi nanay ko aadi."
            ]
          }
        ],
        "story": {
          "id": "u2s1",
          "title": "A Visit to Daram",
          "titleEn": "A Visit to Daram",
          "lines": [
            {
              "war": "Aadi ako ha Daram.",
              "en": "I am here in Daram."
            },
            {
              "war": "Hain hi nanay ko?",
              "en": "Where is my mother?"
            },
            {
              "war": "Aada hi nanay ko. Dadi!",
              "en": "My mother is there. Come here!"
            },
            {
              "war": "Didto hi tatay ko ngan hi apo ko.",
              "en": "My father and my grandchild are over there."
            }
          ],
          "q": {
            "q": "Where is the speaker?",
            "options": [
              "Daram",
              "Samar",
              "Manila"
            ],
            "answer": 0
          }
        }
      },
      {
        "id": "u3",
        "name": "House and Daily Actions",
        "hint": "Home Environment in Daram",
        "lessons": [
          {
            "id": "u3l1",
            "title": "House Parts",
            "items": [
              "balay",
              "kwarto",
              "kusina",
              "pantaw",
              "purtahan",
              "bintana",
              "natad",
              "kudal"
            ]
          },
          {
            "id": "u3l2",
            "title": "Possession and Actions",
            "items": [
              "akon",
              "imo",
              "iyo",
              "sulod",
              "gawas",
              "lingkod",
              "tindog"
            ]
          },
          {
            "id": "u3l3",
            "title": "Using House and Actions",
            "kind": "apply",
            "items": [
              "Sulod ha kwarto.",
              "Lingkod ha pantaw.",
              "Imo balay ini.",
              "Gawas ha natad.",
              "Akon kusina adto."
            ]
          },
          {
            "id": "u3l4",
            "title": "Unit u3 Review",
            "kind": "apply",
            "items": [
              "Tindog ha purtahan.",
              "Iyo bintana adto.",
              "in kudal",
              "Sulod ha balay, akon anak."
            ]
          }
        ],
        "story": {
          "id": "u3s1",
          "title": "Ha Akon Balay",
          "titleEn": "At My House",
          "lines": [
            {
              "war": "Maupay nga aga! Ini in akon balay.",
              "en": "Good day! This is my house."
            },
            {
              "war": "Sulod ha purtahan, tapos lingkod ha pantaw.",
              "en": "Enter the door, then sit on the back porch."
            },
            {
              "war": "Adto in iyo kwarto, ngan didto in akon kusina.",
              "en": "That is your (plural) room, and there is my kitchen."
            },
            {
              "war": "Gawas ha natad, in kudal didto.",
              "en": "Go out to the yard, there is a fence there."
            }
          ],
          "q": {
            "q": "Ano in imo ginsulod?",
            "options": [
              "in bintana",
              "in purtahan",
              "in kudal"
            ],
            "answer": 1
          }
        }
      },
      {
        "id": "u4",
        "name": "Food, Drinks, and Requests",
        "hint": "Staple Needs and Politeness",
        "lessons": [
          {
            "id": "u4l1",
            "title": "Kitchen Staples",
            "items": [
              "tubig",
              "kape",
              "kan-on",
              "isda",
              "utan",
              "prutas",
              "tinapay",
              "sabaw",
              "gusto",
              "kinahanglan"
            ]
          },
          {
            "id": "u4l2",
            "title": "Wants, Actions & Pronouns",
            "items": [
              "alayon",
              "salamat",
              "kaon",
              "inom",
              "init",
              "matugnaw",
              "ko",
              "mo",
              "niya"
            ]
          },
          {
            "id": "u4l3",
            "title": "Making Requests",
            "kind": "apply",
            "items": [
              "Gusto ko hin init nga kape.",
              "Kinahanglan ko hin tubig, alayon.",
              "Kaon hin isda ngan utan.",
              "Gusto mo matugnaw nga prutas?",
              "Inom sin sabaw."
            ]
          },
          {
            "id": "u4l4",
            "title": "Unit u4 Review",
            "kind": "apply",
            "items": [
              "Salamat, gusto ko hin kan-on.",
              "Alayon, gusto ko hin tinapay.",
              "Kinahanglan mo ba matugnaw nga tubig?",
              "Kaon hin prutas ngan inom hin tubig."
            ]
          }
        ],
        "story": {
          "id": "u4s1",
          "title": "Pamahaw ni Lolo Ben",
          "titleEn": "Grandpa Ben's Breakfast",
          "lines": [
            {
              "war": "Hi Lolo Ben gusto hin kape.",
              "en": "Grandpa Ben wants coffee."
            },
            {
              "war": "Kinahanglan niya hin kan-on ngan isda.",
              "en": "He needs some rice and fish."
            },
            {
              "war": "Alayon, gusto niya matugnaw nga tubig.",
              "en": "Please, he wants cold water."
            },
            {
              "war": "Salamat, Lolo Ben maupay.",
              "en": "Thank you, Grandpa Ben is happy."
            }
          ],
          "q": {
            "q": "Ano an gusto ni Lolo Ben inumon?",
            "options": [
              "kape",
              "tubig",
              "sabaw"
            ],
            "answer": 0
          }
        }
      },
      {
        "id": "u5",
        "name": "Numbers and Money",
        "hint": "Small Market Transactions",
        "lessons": [
          {
            "id": "u5l1",
            "title": "Counting 1-10",
            "items": [
              "usa",
              "duha",
              "tulo",
              "upat",
              "lima",
              "unom",
              "pito",
              "walo",
              "siyam",
              "napulo"
            ]
          },
          {
            "id": "u5l2",
            "title": "Asking Price and Money",
            "items": [
              "pira",
              "tagpira",
              "palit",
              "mapalit",
              "bayad",
              "sukli",
              "kwarta",
              "pesos",
              "mahal",
              "barato"
            ]
          },
          {
            "id": "u5l3",
            "title": "Market Transactions",
            "kind": "apply",
            "items": [
              "Tagpira ini nga isda?",
              "Lima ka pesos.",
              "Mapalit ako tulo ka isda.",
              "Mahal ini.",
              "Barato an isda.",
              "Waray ako sukli."
            ]
          },
          {
            "id": "u5l4",
            "title": "Unit u5 Review",
            "kind": "apply",
            "items": [
              "Pira an kwarta mo?",
              "Mapalit ka napulo ka tinapay?",
              "Bayad na! Waray sukli.",
              "Mahal ini nga isda, barato an isda."
            ]
          }
        ],
        "story": {
          "id": "u5s1",
          "title": "Ha Tiangge",
          "titleEn": "At the Market",
          "lines": [
            {
              "war": "Mapalit ako isda.",
              "en": "I will buy fish."
            },
            {
              "war": "Tagpira ini?",
              "en": "How much is this?"
            },
            {
              "war": "Lima ka pesos.",
              "en": "Five pesos."
            },
            {
              "war": "Mahal ini. Barato an isda.",
              "en": "This is expensive. The banana is cheap."
            }
          ],
          "q": {
            "q": "What will the person buy?",
            "options": [
              "Isda",
              "Saging",
              "Kwarta"
            ],
            "answer": 0
          }
        }
      }
    ]
  }
];

export const CH2_LEVELS = {"maupay":"A0","aga":"A0","udto":"A0","kulop":"A0","gab-i":"A0","yana":"A0","kaina":"A0","unina":"A0","kamusta":"A0","ako":"A0","ikaw":"A0","hiya":"A0","hira":"A0","kami":"A0","kita":"A0","nanay":"A0","tatay":"A0","kuya":"A0","ate":"A0","bugto":"A0","asawa":"A0","anak":"A0","apo":"A0","aadi":"A0","aada":"A0","didto":"A0","hain":"A0","oo":"A0","diri":"A0","dadi":"A0","ngadto":"A0","balay":"A0","kwarto":"A0","kusina":"A0","pantaw":"A0","purtahan":"A0","bintana":"A0","natad":"A0","kudal":"A0","akon":"A0","imo":"A0","iyo":"A0","sulod":"A0","gawas":"A0","lingkod":"A0","tindog":"A0","tubig":"A0","kape":"A0","kan-on":"A0","isda":"A0","utan":"A0","prutas":"A0","tinapay":"A0","sabaw":"A0","gusto":"A0","kinahanglan":"A0","alayon":"A0","salamat":"A0","kaon":"A0","inom":"A0","init":"A0","matugnaw":"A0","ko":"A0","mo":"A0","niya":"A0","usa":"A0","duha":"A0","tulo":"A0","upat":"A0","lima":"A0","unom":"A0","pito":"A0","walo":"A0","siyam":"A0","napulo":"A0","pira":"A0","tagpira":"A0","palit":"A0","mapalit":"A0","bayad":"A0","sukli":"A0","kwarta":"A0","pesos":"A0","mahal":"A0","barato":"A0"};
