/* Generate src/courses/waray/stories.js for the in-app Read tab, from the CC/free corpus
   files + the lexicon's glosses. STORIES = display paragraphs per story; GLOSS = waray-norm
   -> english for tap-to-reveal. Run: node tools/build-stories.mjs */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => fs.readFileSync(path.join(root, p), "utf8");

const lex = JSON.parse(read("docs/sources/waray-lexicon.json"));
const GLOSS = {};
for (const l of lex.lexemes) if (l.gloss) GLOSS[l.id] = l.gloss;

const slug = (s) => s.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 40);

function parse(file, marker, source, defLicense, mode) {
  const text = read(file);
  const heads = [...text.matchAll(new RegExp(`===${marker}: ([^=]*)===`, "g"))].map((m) => m[1].trim());
  const chunks = text.split(new RegExp(`===${marker}:[^=]*===`));
  chunks.shift();
  return chunks.map((body, i) => {
    let title = heads[i] || `#${i}`, license = defLicense;
    const lm = title.match(/^(.*?)\s*\[([^\]]+)\]\s*$/);
    if (lm) { title = lm[1].trim(); license = lm[2].trim(); }
    title = title.replace(/_PDA\.pdf$/i, "").replace(/^\d+_/, "").replace(/_/g, " ").replace(/\s+/g, " ").trim();
    let paras;
    if (mode === "lines") paras = body.split("\n").map((s) => s.trim()).filter((s) => s.length > 1);
    else paras = body.replace(/\s+/g, " ").trim().split(/(?<=[.?!])\s+/).map((s) => s.trim()).filter((s) => s.split(" ").length >= 2);
    // drop a leading paragraph that just repeats the title
    if (paras[0] && paras[0].toLowerCase().replace(/\s+/g, "") === title.toLowerCase().replace(/\s+/g, "")) paras.shift();
    return { id: source.toLowerCase() + "-" + slug(title), title, source, license, paras };
  }).filter((s) => s.paras.length >= 2);
}

const raw = [
  ...parse("docs/sources/bloom-waray-stories.txt", "BOOK", "Bloom", "CC", "lines"),
  ...parse("docs/sources/bfc-waray-stories.txt", "STORY", "BFC", "free to copy, not for sale", "sentences"),
];
// merge ChatGPT-authored comprehension data (English title + MC questions), if present
const qPath = path.join(root, "docs/sources/story-questions.json");
const QA = fs.existsSync(qPath) ? JSON.parse(fs.readFileSync(qPath, "utf8")) : {};
for (const s of raw) {
  const q = QA[s.id];
  if (q) { s.titleEn = q.title_en || ""; s.questions = q.questions || []; }
}
// dedup by id (Bloom has re-uploads of the same title under different CC licenses) —
// keep the most complete copy. Guarantees unique ids (= unique React keys).
const byId = new Map();
for (const s of raw) {
  const len = s.paras.join(" ").length;
  const ex = byId.get(s.id);
  if (!ex || len > ex._len) byId.set(s.id, { ...s, _len: len });
}
const STORIES = [...byId.values()].map(({ _len, ...s }) => s);

const out = `/* GENERATED by tools/build-stories.mjs — do not hand-edit.
   Free/CC-licensed Waray stories for the Read tab, with a gloss map for tap-to-reveal.
   Bloom Library books are Creative Commons (per-book license in .license); Bible for
   Children is free to copy/not for sale. Both attributed in-app. */
export const STORIES = ${JSON.stringify(STORIES, null, 1)};

export const GLOSS = ${JSON.stringify(GLOSS)};
`;
fs.writeFileSync(path.join(root, "src/courses/waray/stories.js"), out);
console.log(`stories: ${STORIES.length} | gloss entries: ${Object.keys(GLOSS).length}`);
STORIES.forEach((s) => console.log(`  ${s.source.padEnd(6)} ${s.paras.length}¶  ${s.title}`));
