/* Turn the Gemini-extracted PC blocks (scratchpad/pc-blocks.json) into docs/schema/pc-seed.sql:
   a 'pc' course whose lessons are the block model (grammar/examples/note/vocab + a drill tail).
   PC vocab inserts with ON CONFLICT DO NOTHING so shared words (ako, hiya…) reuse CH2's rows.
   Expression/block ids are offset by 20000 to avoid colliding with the CH2 seed.
   Run: node tools/gen-pc-seed.mjs <path-to-pc-blocks.json>  */
import fs from "fs";
const SRC = process.argv[2] || "/private/tmp/claude-501/-Users-paulkilroy-dev-Sulog/2ec9156d-452e-4eed-b759-f98650a29e43/scratchpad/pc-blocks.json";
const lessons = JSON.parse(fs.readFileSync(SRC, "utf8")).sort((a, b) => a.num - b.num);
const S = (v) => v == null || v === "" ? "null" : "'" + String(v).replace(/'/g, "''") + "'";
const norm = (s) => (s || "").trim();

const dict = new Map();          // waray -> {meaning,pos}
const expr = new Map();          // sentence -> id
let eid = 20000, bid = 20000;
const blocks = [], items = [];
const putExpr = (war, en) => { const w = norm(war); if (!w) return null; if (expr.has(w)) return expr.get(w); const id = ++eid; expr.set(w, id); exprRows.push({ id, war: w, en: en || "" }); return id; };
const exprRows = [];
const addBlock = (lid, ord, type, cols = {}) => { const id = ++bid; blocks.push({ id, lid, ord, type, ...cols }); return id; };

for (const L of lessons) {
  const lid = `pc-l${L.num}`;
  let ord = 0;
  const vocabWords = [];
  for (const b of (L.data.blocks || [])) {
    if (b.type === "grammar") addBlock(lid, ++ord, "grammar", { title: b.title, body: b.prose, formula: b.formula });
    else if (b.type === "note") addBlock(lid, ++ord, "note", { body: b.text });
    else if (b.type === "examples") {
      const bl = addBlock(lid, ++ord, "examples");
      (b.items || []).forEach((e, i) => { const id = putExpr(e.war, e.en); if (id) items.push({ b: bl, ord: i + 1, expr: id, role: "example" }); });
    } else if (b.type === "vocab") {
      const bl = addBlock(lid, ++ord, "vocab");
      (b.items || []).forEach((v, i) => { const w = norm(v.waray); if (!w) return; if (!dict.has(w)) dict.set(w, { meaning: v.meaning, pos: v.pos }); vocabWords.push(w); items.push({ b: bl, ord: i + 1, dict: w, role: "teach" }); });
    }
  }
  // shared drill tail over this lesson's vocab (recognition + production)
  if (vocabWords.length) {
    for (const [dk, dm, dh, dd] of [["recognition", "mc", "peek", null], ["production", "type", "partial", "both"]]) {
      const bl = addBlock(lid, ++ord, "drill", { dkind: dk, dmod: dm, dhint: dh, ddir: dd });
      vocabWords.slice(0, 8).forEach((w, i) => items.push({ b: bl, ord: i + 1, dict: w, role: "item" }));
    }
  }
}

const out = [];
out.push("-- GENERATED by tools/gen-pc-seed.mjs from Gemini-extracted PC blocks. AI-extracted from");
out.push("-- noisy OCR — everything confirmed=false (needs review). Load AFTER schema.sql + seed.sql.\n");
out.push("insert into courses values ('pc','Peace Corps Waray','war','grammar-spine') on conflict (id) do nothing;");
out.push("insert into phases values ('pc-p1','pc',1,'Foundations (Lessons 1–10)','equational sentences & the pronoun classes') on conflict (id) do nothing;");
out.push("insert into units values ('pc-u1','pc-p1',1,'Pronoun classes & verbs',null,null) on conflict (id) do nothing;");
out.push("insert into lessons (id,unit_id,ord,title) values\n" + lessons.map((L, i) => `  ('pc-l${L.num}','pc-u1',${i + 1},${S(L.name)})`).join(",\n") + " on conflict (id) do nothing;");
out.push("insert into dictionary (waray,kind,meaning,pos,confirmed) values\n" + [...dict].map(([w, d]) => `  (${S(w)},'word',${S(d.meaning)},${S(d.pos)},false)`).join(",\n") + "\n  on conflict (waray) do nothing;");
if (exprRows.length) out.push("insert into expressions (id,waray,translation) values\n" + exprRows.map((e) => `  (${e.id},${S(e.war)},${S(e.en)})`).join(",\n") + " on conflict (id) do nothing;");
out.push("insert into lesson_blocks (id,lesson_id,ord,type,title,body_md,formula,drill_kind,drill_modality,drill_hint,drill_direction) values\n" +
  blocks.map((b) => `  (${b.id},${S(b.lid)},${b.ord},${S(b.type)},${S(b.title)},${S(b.body)},${S(b.formula)},${S(b.dkind)},${S(b.dmod)},${S(b.dhint)},${S(b.ddir)})`).join(",\n") + " on conflict (id) do nothing;");
out.push("insert into block_items (block_id,ord,dict_waray,expr_id,role) values\n" +
  items.map((it) => `  (${it.b},${it.ord},${S(it.dict)},${it.expr ?? "null"},${S(it.role)})`).join(",\n") + ";");

fs.writeFileSync("docs/schema/pc-seed.sql", out.join("\n\n") + "\n");
console.log(`✓ pc-seed.sql — ${lessons.length} lessons · dictionary +${dict.size} · expressions +${exprRows.length} · blocks +${blocks.length} · items +${items.length}`);
