/* Ingest ChatGPT's first-pass gloss verdicts (docs/sources/gloss-reply.json):
   - verdict "waray"  -> gloss = def
   - verdict "other"  -> gloss = "def (Lang)"
   -> written to src/courses/waray/gloss-extra.js (GLOSS_EXTRA), merged by build-stories.
   - verdict "scan"   -> token-wise text correction in the Bloom source (NOT a gloss),
     except SCAN_HOLD words we don't trust yet (reported, not applied).
   - verdict "unknown" + held items -> printed for Ella.
   Our CORRECTIONS override GPT where our own dictionary disagrees. Re-runnable.
   Run: node tools/ingest-gloss.mjs */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const rp = (p) => path.join(root, p);
const reply = JSON.parse(fs.readFileSync(rp("docs/sources/gloss-reply.json"), "utf8"));

// our overrides: GPT mislabeled these Tagalog, but the root is Waray in our dictionary
const CORRECTIONS = {
  uminom:       { verdict: "waray", def: "drank (inom = drink)" },
  "nag-iiba":   { verdict: "waray", def: "changing (iba = other/different)" },
  nangunguna:   { verdict: "waray", def: "leading; going first (una = first)" },
};
// scan-fixes we are NOT confident enough to auto-apply to the corpus (review w/ Ella)
const SCAN_HOLD = new Set(["ngaha", "makakag-uyas"]);

for (const r of reply) if (CORRECTIONS[r.w]) Object.assign(r, CORRECTIONS[r.w], { fix: "", lang: "" });

// --- build GLOSS_EXTRA (waray + other) ---
const extra = {};
for (const r of reply) {
  if (r.verdict === "waray" && r.def) extra[r.w] = r.def;
  else if (r.verdict === "other" && r.def) extra[r.w] = `${r.def}${r.lang ? ` (${r.lang})` : ""}`;
}
const js = `/* GENERATED by tools/ingest-gloss.mjs from docs/sources/gloss-reply.json —
   ChatGPT first-pass glosses for reader words our dictionary couldn't reach, with our
   corrections applied. Merged by build-stories (below curated GLOSS_FIX). Pending Ella. */
export const GLOSS_EXTRA = ${JSON.stringify(extra, null, 1)};
`;
fs.writeFileSync(rp("src/courses/waray/gloss-extra.js"), js);

// --- apply scan-fixes to the Bloom source, token-wise (safe vs hyphens/punctuation) ---
const norm = (t) => (t || "").toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/[’`]/g, "'");
const scans = reply.filter((r) => r.verdict === "scan" && r.fix);
const fixMap = new Map(scans.filter((r) => !SCAN_HOLD.has(r.w)).map((r) => [r.w, r.fix]));
const srcPath = rp("docs/sources/bloom-waray-stories.txt");
let text = fs.readFileSync(srcPath, "utf8");
const counts = {};
text = text.split(/(\s+)/).map((piece) => {
  if (/^\s+$/.test(piece) || !piece) return piece;
  const lead = (piece.match(/^[^A-Za-zÀ-ÿ]*/) || [""])[0];
  const trail = (piece.match(/[^A-Za-zÀ-ÿ]*$/) || [""])[0];
  const core = piece.slice(lead.length, piece.length - trail.length);
  const key = norm(core).replace(/^['\-]+|['\-]+$/g, "");
  if (fixMap.has(key)) { counts[key] = (counts[key] || 0) + 1; return lead + fixMap.get(key) + trail; }
  return piece;
}).join("");
fs.writeFileSync(srcPath, text);

// --- report ---
const tally = {};
for (const r of reply) tally[r.verdict] = (tally[r.verdict] || 0) + 1;
const lines = [`# Gloss ingest report`, ``, `verdicts: ${JSON.stringify(tally)}`, ``,
  `## Glosses added (${Object.keys(extra).length}) → src/courses/waray/gloss-extra.js`, ``,
  `## Scan-fixes APPLIED to bloom-waray-stories.txt`, ...scans.filter((r) => !SCAN_HOLD.has(r.w)).map((r) => `- \`${r.w}\` → \`${r.fix}\`  (${counts[r.w] || 0}×)`), ``,
  `## Scan-fixes HELD for review (not applied)`, ...scans.filter((r) => SCAN_HOLD.has(r.w)).map((r) => `- \`${r.w}\` → \`${r.fix}\` ?`), ``,
  `## Our corrections over ChatGPT`, ...Object.entries(CORRECTIONS).map(([w, c]) => `- \`${w}\`: GPT said other/Tagalog → we say ${c.verdict}: ${c.def}`)];
fs.writeFileSync(rp("docs/sources/gloss-ingest-report.md"), lines.join("\n") + "\n");

console.log(`gloss-extra: ${Object.keys(extra).length} entries`);
console.log(`scan-fixes applied: ${[...fixMap.keys()].join(", ")}`);
console.log(`scan-fixes held: ${[...SCAN_HOLD].join(", ")}`);
console.log(`occurrences:`, counts);
