#!/usr/bin/env node
/* Ingestion: reload the Peace Corps course into the live DB from docs/schema/pc-seed.sql,
 * then regenerate the "Course vs. Book" verification page so it always reflects what's live.
 *
 * Pipeline:  node tools/gen-pc-seed.mjs      # rebuild pc-seed.sql from the Gemini blocks
 *            node tools/reload-pc.mjs        # THIS: load it, bump version, regen the preview
 *
 * One transaction: purge the old pc-* rows, load the fresh seed, drop orphaned unconfirmed
 * dictionary rows (parser artifacts), and bump courses.version so every connected app
 * auto-refetches its cache. Requires SUPABASE_DB_URL (never hardcode the password).
 */
import pg from "pg";
import fs from "fs";
import { execSync } from "child_process";

// ---- preflight guards: this script REWRITES live course content, so fail fast on the classic
// accidents — wrong database, or a stale/broken/truncated seed file. --force skips the shrinkage
// guard for intentional content removals.
const EXPECTED_REF = "kdtzfaobcgprivsxkger"; // the Sulog Supabase project
if (!(process.env.SUPABASE_DB_URL || "").includes(EXPECTED_REF))
  { console.error(`✗ SUPABASE_DB_URL does not point at project ${EXPECTED_REF} — refusing to reload.`); process.exit(1); }
const seed = fs.readFileSync("docs/schema/pc-seed.sql", "utf8");
for (const marker of ["insert into lessons", "insert into block_items", "'pc-l1a'", "GENERATED by tools/gen-pc-seed.mjs"])
  if (!seed.includes(marker)) { console.error(`✗ pc-seed.sql looks broken/truncated (missing "${marker}") — refusing to reload.`); process.exit(1); }
const seedLessons = (seed.match(/\('pc-l[0-9]+[ab]?'/g) || []).length;

const c = new pg.Client({ connectionString: process.env.SUPABASE_DB_URL, ssl: { rejectUnauthorized: false }, connectionTimeoutMillis: 15000 });
await c.connect();
const one = async (s) => (await c.query(s)).rows[0];
const counts = "select (select count(*) from lessons where id like 'pc-%') l, (select count(*) from lesson_blocks where lesson_id like 'pc-%') b, (select count(*) from block_items bi join lesson_blocks lb on lb.id=bi.block_id where lb.lesson_id like 'pc-%') i, (select count(*) from expressions where id>=20000) e";
const before = await one(counts);
console.log("BEFORE:", before);
// shrinkage guard: a seed with meaningfully fewer lessons than the live DB usually means a stale or
// half-regenerated source (e.g. the extraction file went missing) — not an intentional edit
if (seedLessons < Number(before.l) && !process.argv.includes("--force")) {
  console.error(`✗ seed has ${seedLessons} lessons but the live DB has ${before.l} — pass --force if this shrink is intentional.`);
  await c.end(); process.exit(1);
}

try {
  await c.query("begin");
  // remember which dictionary rows the OUTGOING pc load referenced — the post-load purge is scoped to
  // exactly this set, so it can only ever remove stale PC words, never the shared word bank / other courses'
  // lexicon entries (a broad "unconfirmed and unreferenced" sweep once deleted 415 word-bank rows).
  await c.query(`create temp table _pc_dict on commit drop as
      select distinct bi.dict_waray as waray from block_items bi
      join lesson_blocks lb on lb.id = bi.block_id
      where lb.lesson_id like 'pc-%' and bi.dict_waray is not null`);
  await c.query("update lesson_blocks set review_target=null where lesson_id like 'pc-%'"); // drop self-refs first
  await c.query("delete from block_items where block_id in (select id from lesson_blocks where lesson_id like 'pc-%')");
  await c.query("delete from lesson_blocks where lesson_id like 'pc-%'");
  await c.query("delete from lessons where id like 'pc-%'");
  await c.query("delete from units where id like 'pc-%'");
  await c.query("delete from phases where id like 'pc-%'");
  await c.query("delete from expressions where id >= 20000");
  await c.query("delete from courses where id='pc'");
  await c.query("delete from dictionary where waray like '-%' and confirmed=false"); // stale hyphen roots from a buggy load
  await c.query(seed); // fresh pc-seed.sql
  // purge dictionary rows the old PC load referenced that the new one no longer does (words dropped
  // from the seed). Scoped to _pc_dict so nothing outside PC can ever be touched; still requires
  // unconfirmed + unreferenced anywhere; and a word whose `meanings` carry any non-PC source
  // (word bank, tramp, ella…) is protected — deleting it would cascade those senses away.
  const purged = await c.query(`delete from dictionary d where confirmed=false
      and d.waray in (select waray from _pc_dict)
      and not exists (select 1 from block_items   bi where bi.dict_waray=d.waray)
      and not exists (select 1 from expressions    e where e.focus=d.waray)
      and not exists (select 1 from lesson_blocks lb where lb.about=d.waray)
      and not exists (select 1 from meanings m where m.waray=d.waray and (m.confirmed or not (m.sources <@ array['pc']::text[])))
      returning waray`);
  console.log("purged", purged.rowCount, "orphaned dict rows:", purged.rows.map((r) => r.waray).join(", "));
  // seeds insert EXPLICIT ids into bigserial columns, which leaves the sequences behind — the first
  // nextval-based insert would collide on a low id. Re-sync them after every load.
  for (const t of ["expressions", "lesson_blocks", "block_items", "meanings"])
    await c.query(`select setval(pg_get_serial_sequence('${t}','id'), coalesce((select max(id) from ${t}), 1))`);
  // bump the course version so every connected app auto-refreshes its cached copy on next load
  await c.query("update courses set version = (extract(epoch from clock_timestamp())*1000)::bigint where id='pc'");
  await c.query("commit");
  console.log("✓ committed");
} catch (e) { await c.query("rollback"); console.error("✗ rolled back:", e.message); process.exit(1); }

console.log("AFTER: ", await one(counts));
await c.end();

// regenerate the side-by-side verification page from the now-live DB
console.log("\nregenerating course preview…");
execSync("node tools/gen-course-preview.mjs", { stdio: "inherit", env: process.env });

// auto-confirm PC dictionary entries whose extracted gloss matches the book's own printed text —
// the book's authority carries; only unverifiable extractions stay in Ella's queue
console.log("\nconfirming PC entries against the book…");
execSync("node tools/confirm-from-book.mjs --apply", { stdio: "inherit", env: process.env });

// prove RLS still guards the public key (a recreated table comes back unprotected — this is the alarm)
console.log("\nRLS smoke test…");
execSync("node tools/rls-smoke.mjs", { stdio: "inherit" });
